/**
 * 产品目录结构定义（Solo Monorepo）
 *
 * 严格对照 KNOWLEDGE-LIFECYCLE.md §7.1-7.4 + §8.3
 * 导出 buildProductFileList(productName, appName) 生成完整文件清单
 */

// ─── 工具函数 ────────────────────────────────────────────────────────────────

/** 将任意字符串转为 kebab-case */
function toKebabCase(str: string): string {
  return str
    .trim()
    .replace(/[\s_]+/g, '-')
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9\u4e00-\u9fff-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

/** 生成 Agent 定义 .md 文件内容（frontmatter + 描述）*/
function agentMdContent(
  id: string, name: string, emoji: string,
  color: string, bgColor: string, borderColor: string,
  skills: string[], desc: string,
): string {
  return [
    '---', `id: ${id}`, `name: ${name}`, `role: ${name}`,
    `emoji: "${emoji}"`, `color: "${color}"`, `bgColor: "${bgColor}"`, `borderColor: "${borderColor}"`,
    'skills:', ...skills.map(s => `  - ${s}`), '---', desc, '',
  ].join('\n');
}

// ─── 文件条目类型 ─────────────────────────────────────────────────────────────

export interface ProductFileEntry {
  /** 相对于 workDir 的路径 */
  path: string;
  /** 文件初始内容 */
  content: string;
}

// ─── 内容生成辅助函数 ─────────────────────────────────────────────────────────

const EMPTY = '';
const INDEX_YAML = 'items: []\n';

function mdFrontmatter(meta: Record<string, string>): string {
  const lines = Object.entries(meta).map(([k, v]) => `${k}: ${v}`);
  return `---\n${lines.join('\n')}\n---\n\n`;
}

function overviewMd(title: string, description: string): string {
  return mdFrontmatter({ title, lifecycle: 'living', 'created-at': new Date().toISOString().slice(0, 10) })
    + `# ${title}\n\n${description}\n`;
}

function knowledgeMd(title: string): string {
  return mdFrontmatter({ title, lifecycle: 'living', 'created-at': new Date().toISOString().slice(0, 10) })
    + `# ${title}\n`;
}

function roadmapMd(scope: string): string {
  return mdFrontmatter({ title: `${scope} Roadmap`, lifecycle: 'living', 'created-at': new Date().toISOString().slice(0, 10) })
    + `# ${scope} Roadmap\n\n## Milestones\n\n_TODO_\n`;
}

function emptyYaml(): string {
  return '# Auto-generated by xingjing\n';
}

function ownersFile(name: string): string {
  return `# ${name}\n# Add owner GitHub handles below\n`;
}

function readmeFile(title: string, description: string): string {
  return `# ${title}\n\n${description}\n`;
}

// ─── 知识规约内容生成 ─────────────────────────────────────────────────────────

type ProductMode = 'solo' | 'team';
interface PathCtx { mode: ProductMode; pl: string; domain: string; app: string; }
function appPfx(ctx: PathCtx): string { return `apps/${ctx.app}`; }

/** 生成产品根目录 AGENTS.md（角色-目录映射、文档链路、命名规范） */
function buildAgentsMd(ctx: PathCtx): string {
  const a = appPfx(ctx);
  const { pl, domain, mode } = ctx;
  const tree = mode === 'solo' ? [
    `├── governance-standards/    平台层`,
    `├── ${pl}/                   产品线层`,
    `├── ${domain}/               领域层`,
    `├── ${a}/                    应用层`,
    `├── .opencode/               Agent + Skill`,
    `└── AGENTS.md`,
  ] : [
    `├── ${pl}/                   产品线仓库`,
    `├── ${domain}/               领域仓库`,
    `├── ${a}/                    应用仓库`,
    `├── .opencode/               Agent + Skill`,
    `└── AGENTS.md`,
  ];
  return [
    `# AGENTS.md — 知识管理规约`,
    ``,
    `> 所有 Agent 在生成任何文档前 **MUST** 遵循此规约。`,
    ``,
    `## 目录结构（${mode === 'solo' ? 'Solo Monorepo' : 'Team 多仓库'}）`,
    ``,
    '```',
    ...tree,
    '```',
    ``,
    `## 角色-目录所有权`,
    ``,
    `| Agent | 输出目录 | 产出类型 |`,
    `|-------|---------|---------|`,
    `| product-brain | \`${pl}/strategy/prd/\` \`${a}/docs/product/prd/\` \`${pl}/docs/journeys/\` \`${pl}/knowledge/scenarios/\` \`${pl}/docs/help-center/guides/\` | PRD, 战略PRD, JOURNEY, SCENARIO, GUIDE, Roadmap |`,
    `| eng-brain | \`${a}/docs/product/architecture/\` \`${a}/docs/product/contracts/\` \`${a}/docs/features/\` \`${a}/docs/delivery/plan/\` \`${a}/docs/delivery/task/\` | SDD, MODULE, OpenAPI, FORM, PLAN, TASK, Helm |`,
    `| growth-brain | \`${pl}/strategy/research/\` \`${pl}/docs/help-center/\` | BENCHMARK, MARKET, CUSTOMER, FAQ, RN |`,
    `| ops-brain | \`${a}/docs/ops/runbook/\` \`${a}/docs/delivery/releases/\` \`${domain}/docs/qa/reports/\` | Runbook, RELEASE, TR |`,
    ``,
    `## 文档链路约束`,
    ``,
    '```',
    `PRD (approved) → SDD (approved) → MODULE (approved) → PLAN → TASK → Code`,
    '```',
    ``,
    `## 命名规范`,
    ``,
    `| 类别 | 格式 | 示例 |`,
    `|------|------|------|`,
    `| 基线 | \`{TYPE}-{NNN}-{name}.md\` | PRD-001-user-login.md |`,
    `| 交付 | \`{TYPE}-{VER}-{NNN}-{name}.md\` | PLAN-v1.0-001-mvp.md |`,
    `| 研究 | \`{TYPE}-{YYYYQN}-{NNN}-{name}.md\` | BENCHMARK-2026Q2-001-x.md |`,
    ``,
    `## 台账规则`,
    ``,
    `生成文档后 **MUST** 更新同目录 \`_index.yaml\`。`,
    `所有 Agent 生成文档前 **MUST** 调用 \`knowledge-conventions\` skill。`,
    ``,
  ].join('\n');
}

/** 生成增强版 Agent 定义（含知识产出目录映射表） */
function enhancedAgentContent(
  id: string, name: string, emoji: string,
  color: string, bgColor: string, borderColor: string,
  skills: string[], desc: string, outputTable: string,
): string {
  return [
    '---', `id: ${id}`, `name: ${name}`, `role: ${name}`,
    `emoji: "${emoji}"`, `color: "${color}"`, `bgColor: "${bgColor}"`, `borderColor: "${borderColor}"`,
    'skills:', ...skills.map(s => `  - ${s}`),
    '---', '', desc, '',
    '## 知识产出规则（CRITICAL）', '',
    '在生成任何文档之前，**MUST** 先调用 `knowledge-conventions` skill。', '',
    '### 我的输出目录', '',
    '| 文档类型 | 输出路径 | 命名格式 |',
    '|---------|---------|---------|',
    outputTable, '',
    '### 生成后检查清单', '',
    '- [ ] 文件在正确目录',
    '- [ ] 命名符合规范',
    '- [ ] 已更新 _index.yaml 台账',
    '- [ ] 上游文档状态满足要求',
    '',
  ].join('\n');
}

function productBrainTable(ctx: PathCtx): string {
  const a = appPfx(ctx); const { pl } = ctx;
  return [
    `| PRD | \`${a}/docs/product/prd/\` | PRD-{NNN}-{name}.md |`,
    `| 战略PRD | \`${pl}/strategy/prd/\` | SPRD-{NNN}-{name}.md |`,
    `| JOURNEY | \`${a}/docs/journeys/\` 或 \`${pl}/docs/journeys/\` | JOURNEY-{NNN}-{name}.md |`,
    `| SCENARIO | \`${pl}/knowledge/scenarios/\` | SCENARIO-{NNN}-{name}.md |`,
    `| GUIDE | \`${pl}/docs/help-center/guides/\` | GUIDE-{NNN}-{name}.md |`,
    `| Roadmap | \`${a}/docs/delivery/roadmap.md\` | 原地更新 |`,
  ].join('\n');
}

function engBrainTable(ctx: PathCtx): string {
  const a = appPfx(ctx);
  return [
    `| SDD | \`${a}/docs/product/architecture/\` | SDD-{NNN}-{name}.md |`,
    `| MODULE | \`${a}/docs/product/contracts/\` | MODULE-{NNN}-{name}.md |`,
    `| OpenAPI | \`${a}/docs/product/contracts/openapi/\` | {service}-{ver}.yaml |`,
    `| FORM | \`${a}/docs/features/{feat}/forms/{form}/\` | FORM-{NNN}-{name}.md |`,
    `| schema | \`${a}/docs/features/{feat}/forms/{form}/\` | schema.yaml |`,
    `| PLAN | \`${a}/docs/delivery/plan/\` | PLAN-{VER}-{NNN}-{name}.md |`,
    `| TASK | \`${a}/docs/delivery/task/\` | TASK-{VER}-{NNN}-{NN}-{name}.md |`,
    `| Helm | \`${a}/helm/values/\` | {env}.yaml |`,
  ].join('\n');
}

function growthBrainTable(ctx: PathCtx): string {
  const { pl } = ctx;
  return [
    `| BENCHMARK | \`${pl}/strategy/research/\` | BENCHMARK-{YYYYQN}-{NNN}-{name}.md |`,
    `| MARKET | \`${pl}/strategy/research/\` | MARKET-{YYYYQN}-{NNN}-{name}.md |`,
    `| CUSTOMER | \`${pl}/strategy/research/\` | CUSTOMER-{YYYYQN}-{NNN}-{name}.md |`,
    `| GUIDE | \`${pl}/docs/help-center/guides/\` | GUIDE-{NNN}-{name}.md |`,
    `| FAQ | \`${pl}/docs/help-center/faq/\` | FAQ-{topic}.md |`,
    `| RN | \`${pl}/docs/help-center/release-notes/\` | RN-{version}.md |`,
    `| GAP | \`${pl}/strategy/gap-analysis/\` | GAP-{YYYYQN}-{NNN}-{name}.md |`,
  ].join('\n');
}

function opsBrainTable(ctx: PathCtx): string {
  const a = appPfx(ctx); const { domain } = ctx;
  return [
    `| Runbook | \`${a}/docs/ops/runbook/\` | deployment.md / incident-response.md / monitoring.md |`,
    `| RELEASE | \`${a}/docs/delivery/releases/\` | RELEASE-{version}.md |`,
    `| TR | \`${domain}/docs/qa/reports/\` | TR-{VER}-{NNN}-{name}.md |`,
    `| 风险登记 | \`${a}/docs/delivery/risk-register.md\` | 原地更新 |`,
  ].join('\n');
}

/** 生成 knowledge-conventions Skill 完整内容 */
function buildKnowledgeSkill(ctx: PathCtx): string {
  const a = appPfx(ctx);
  const { pl, domain, mode } = ctx;
  return [
    '---',
    'name: knowledge-conventions',
    'description: 知识管理规约 — 在生成任何文档前调用此 Skill 获取正确的放置路径和命名格式',
    '---', '',
    '# 知识管理规约', '',
    '> **调用时机**：在生成任何文档前 MUST 调用本 Skill 确认放置路径、命名格式、上游状态和台账更新。', '',
    `## 六层路径速查（${mode === 'solo' ? 'Solo' : 'Team'}）`, '',
    '| 层级 | 路径 | 职责 |',
    '|------|------|------|',
    '| 平台层 | `governance-standards/` | Schema、模板、质量门禁 |',
    `| 产品线层 | \`${pl}/\` | 跨域知识、战略PRD、帮助中心 |`,
    `| 领域层 | \`${domain}/\` | 域内知识、测试资产 |`,
    `| 应用层 | \`${a}/docs/\` | PRD/SDD/MODULE/PLAN/TASK |`,
    `| 特性层 | \`${a}/docs/features/{feature}/\` | 特性聚合 |`,
    `| 表单层 | \`${a}/docs/features/{feature}/forms/{form}/\` | DDD 最小颗粒度 |`,
    '',
    '## 基线文档放置（原地更新）', '',
    '| 类型 | 路径 | 命名 | 台账 |',
    '|------|------|------|------|',
    `| PRD | \`${a}/docs/product/prd/\` | PRD-{NNN}-{name}.md | _index.yaml |`,
    `| SDD | \`${a}/docs/product/architecture/\` | SDD-{NNN}-{name}.md | _index.yaml |`,
    `| MODULE | \`${a}/docs/product/contracts/\` | MODULE-{NNN}-{name}.md | _index.yaml |`,
    `| OpenAPI | \`${a}/docs/product/contracts/openapi/\` | {service}-{ver}.yaml | — |`,
    `| FORM | \`${a}/docs/features/{feat}/forms/{form}/\` | FORM-{NNN}-{name}.md | — |`,
    `| schema | \`${a}/docs/features/{feat}/forms/{form}/\` | schema.yaml | — |`,
    `| JOURNEY | \`${a}/docs/journeys/\` 或 \`${pl}/docs/journeys/\` | JOURNEY-{NNN}-{name}.md | — |`,
    `| SCENARIO | \`${pl}/knowledge/scenarios/\` | SCENARIO-{NNN}-{name}.md | — |`,
    `| GLOSSARY | \`${pl}/knowledge/GLOSSARY.md\` 或 \`${domain}/knowledge/GLOSSARY.md\` | 原地更新 | — |`,
    `| Runbook | \`${a}/docs/ops/runbook/\` | {type}.md（原地更新） | — |`,
    `| GUIDE | \`${pl}/docs/help-center/guides/\` | GUIDE-{NNN}-{name}.md | — |`,
    `| FAQ | \`${pl}/docs/help-center/faq/\` | FAQ-{topic}.md | — |`,
    `| TS | \`${pl}/docs/help-center/troubleshooting/\` | TS-{NNN}-{name}.md | — |`,
    '',
    '## 过程文档 — 交付类（按版本归档）', '',
    '| 类型 | 路径 | 命名 | 台账 |',
    '|------|------|------|------|',
    `| PLAN | \`${a}/docs/delivery/plan/\` | PLAN-{VER}-{NNN}-{name}.md | _index.yaml |`,
    `| TASK | \`${a}/docs/delivery/task/\` | TASK-{VER}-{NNN}-{NN}-{name}.md | _index.yaml |`,
    `| RELEASE | \`${a}/docs/delivery/releases/\` | RELEASE-{version}.md | _index.yaml |`,
    `| TR | \`${domain}/docs/qa/reports/\` | TR-{VER}-{NNN}-{name}.md | _index.yaml |`,
    `| TC | \`${domain}/docs/qa/test-cases/\` | TC-{NNN}-{name}.md | _index.yaml |`,
    `| TP | \`${domain}/docs/qa/test-plans/\` | TP-{NNN}-{name}.md | — |`,
    '',
    '## 过程文档 — 研究类（按季度归档）', '',
    '| 类型 | 路径 | 命名 | 台账 |',
    '|------|------|------|------|',
    `| BENCHMARK | \`${pl}/strategy/research/\` | BENCHMARK-{YYYYQN}-{NNN}-{name}.md | _index.yaml |`,
    `| MARKET | \`${pl}/strategy/research/\` | MARKET-{YYYYQN}-{NNN}-{name}.md | _index.yaml |`,
    `| CUSTOMER | \`${pl}/strategy/research/\` | CUSTOMER-{YYYYQN}-{NNN}-{name}.md | _index.yaml |`,
    `| GAP | \`${pl}/strategy/gap-analysis/\` | GAP-{YYYYQN}-{NNN}-{name}.md | — |`,
    `| RN | \`${pl}/docs/help-center/release-notes/\` | RN-{version}.md | — |`,
    '',
    '## 文档链路约束', '',
    '```',
    'PRD (approved) → SDD (approved) → MODULE (approved) → PLAN → TASK → Code',
    '```', '',
    '变更已有功能：直接更新活文档，递增 revision，记录 change_history。', '',
    '## 台账 _index.yaml 结构', '',
    '```yaml',
    'items:',
    '  - id: PRD-001',
    '    title: 用户登录',
    '    status: draft    # draft | in-review | approved | deprecated',
    '    owner: product-brain',
    '    refs: []',
    '    updated: 2026-04-15',
    '```', '',
    '## knowledge/ lifecycle 管理', '',
    '```yaml',
    '---',
    'lifecycle: living    # living | stable',
    'last_updated: 2026-04-15',
    'confirmed_by: null   # stable 时填写',
    '---',
    '```', '',
  ].join('\n');
}

/** 生成产品工作区的全部知识规约文件（AGENTS.md + 4 Agent + Skill） */
function buildKnowledgeAgentFiles(ctx: PathCtx): ProductFileEntry[] {
  return [
    { path: 'AGENTS.md', content: buildAgentsMd(ctx) },
    { path: '.opencode/agents/product-brain.md', content: enhancedAgentContent(
      'product-brain', 'AI产品搭档', '🧠', '#1264e5', '#e6f0ff', '#91c5ff',
      ['需求分析', '假设拆解', '用户洞察', '功能优先级', 'knowledge-conventions'],
      '以产品经理视角分析目标，拆解为可验证的假设和功能点。',
      productBrainTable(ctx),
    ) },
    { path: '.opencode/agents/eng-brain.md', content: enhancedAgentContent(
      'eng-brain', 'AI工程搭档', '⚙️', '#08979c', '#e6fffb', '#87e8de',
      ['技术方案', '代码实现', 'Bug 修复', '部署执行', 'knowledge-conventions'],
      '选择最简技术方案，直接生成可运行代码，无需评审。',
      engBrainTable(ctx),
    ) },
    { path: '.opencode/agents/growth-brain.md', content: enhancedAgentContent(
      'growth-brain', 'AI增长搭档', '📈', '#d46b08', '#fff7e6', '#ffd591',
      ['用户获取', '留存策略', '文案生成', '社区运营', 'knowledge-conventions'],
      '制定增长策略，生成营销文案，规划用户触达方案。',
      growthBrainTable(ctx),
    ) },
    { path: '.opencode/agents/ops-brain.md', content: enhancedAgentContent(
      'ops-brain', 'AI运营搭档', '🔧', '#389e0d', '#f6ffed', '#b7eb8f',
      ['数据监控', '发布管理', '客服回复', '故障处理', 'knowledge-conventions'],
      '监控生产环境，处理用户反馈，执行日常运营任务。',
      opsBrainTable(ctx),
    ) },
    { path: '.opencode/skills/knowledge-conventions/SKILL.md', content: buildKnowledgeSkill(ctx) },
  ];
}

// ─── §7.1 平台层 governance-standards/ ─────────────────────────────────────

function buildGovernanceStandards(): ProductFileEntry[] {
  const p = (f: string) => `governance-standards/${f}`;
  return [
    // schemas/
    { path: p('schemas/prd-schema.json'), content: '{}' },
    { path: p('schemas/sdd-schema.json'), content: '{}' },
    { path: p('schemas/contract-schema.json'), content: '{}' },
    { path: p('schemas/plan-schema.json'), content: '{}' },
    { path: p('schemas/strategy-prd-schema.json'), content: '{}' },
    { path: p('schemas/benchmark-schema.json'), content: '{}' },
    // templates/
    { path: p('templates/PRD-template.md'), content: '# PRD Template\n' },
    { path: p('templates/SDD-template.md'), content: '# SDD Template\n' },
    { path: p('templates/CONTRACT-template.md'), content: '# CONTRACT Template\n' },
    { path: p('templates/PLAN-template.md'), content: '# PLAN Template\n' },
    { path: p('templates/TASK-template.md'), content: '# TASK Template\n' },
    { path: p('templates/STRATEGY-PRD-template.md'), content: '# Strategy PRD Template\n' },
    { path: p('templates/BENCHMARK-template.md'), content: '# BENCHMARK Template\n' },
    { path: p('templates/FEATURE-template.md'), content: '# FEATURE Template\n' },
    { path: p('templates/RUNBOOK-template.md'), content: '# RUNBOOK Template\n' },
    { path: p('templates/ROADMAP-template.md'), content: '# ROADMAP Template\n' },
    { path: p('templates/PIPELINE-template.yaml'), content: emptyYaml() },
    { path: p('templates/_index-template.yaml'), content: INDEX_YAML },
    { path: p('templates/platform-adapters/.gitkeep'), content: EMPTY },
    { path: p('templates/scaffold/.gitkeep'), content: EMPTY },
    // quality-gates/
    { path: p('quality-gates/sdd-completeness.yaml'), content: emptyYaml() },
    { path: p('quality-gates/ci-gates.yaml'), content: emptyYaml() },
    { path: p('quality-gates/security-compliance.yaml'), content: emptyYaml() },
    { path: p('quality-gates/engineering-metrics.yaml'), content: emptyYaml() },
    // conventions/
    { path: p('conventions/naming.yaml'), content: emptyYaml() },
    { path: p('conventions/versioning.yaml'), content: emptyYaml() },
    { path: p('conventions/branching.yaml'), content: emptyYaml() },
    // capabilities/
    { path: p('capabilities/agents/.gitkeep'), content: EMPTY },
    { path: p('capabilities/skills/.gitkeep'), content: EMPTY },
    { path: p('capabilities/platform-overlays/.gitkeep'), content: EMPTY },
    { path: p('capabilities/registry.yaml'), content: emptyYaml() },
  ];
}

// ─── §7.2 产品线层 {pl}/ ──────────────────────────────────────────────────

function buildProductLine(pl: string, productName: string): ProductFileEntry[] {
  const p = (f: string) => `${pl}/${f}`;
  return [
    // docs/
    { path: p('docs/overview.md'), content: overviewMd(`${productName} 产品线`, '产品线概述：背景、愿景、管辖领域、核心目标。') },
    { path: p('docs/VIEWS.yaml'), content: emptyYaml() },
    { path: p('docs/features/.gitkeep'), content: EMPTY },
    { path: p('docs/journeys/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/guides/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/faq/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/troubleshooting/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/release-notes/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/roadmap.md'), content: roadmapMd(`${productName} 产品线交付`) },
    { path: p('docs/delivery/breakdown/strategy-status.yaml'), content: INDEX_YAML },
    // knowledge/
    { path: p('knowledge/GLOSSARY.md'), content: knowledgeMd('跨域统一语言词汇表') },
    { path: p('knowledge/context-map.md'), content: knowledgeMd('领域间边界地图') },
    { path: p('knowledge/data-model.md'), content: knowledgeMd('跨域共享数据模型') },
    { path: p('knowledge/integration-patterns.md'), content: knowledgeMd('跨域集成规范') },
    { path: p('knowledge/shared-events.yaml'), content: emptyYaml() },
    { path: p('knowledge/scenarios/.gitkeep'), content: EMPTY },
    { path: p('knowledge/adr/.gitkeep'), content: EMPTY },
    // strategy/
    { path: p('strategy/roadmap.md'), content: roadmapMd(`${productName} 战略`) },
    { path: p('strategy/prd/_index.yaml'), content: INDEX_YAML },
    { path: p('strategy/gap-analysis/.gitkeep'), content: EMPTY },
    { path: p('strategy/research/_index.yaml'), content: INDEX_YAML },
    { path: p('strategy/research/archive/.gitkeep'), content: EMPTY },
    // registry/
    { path: p('registry/domains.yaml'), content: emptyYaml() },
    { path: p('registry/domain-status.yaml'), content: emptyYaml() },
    { path: p('registry/strategy-status.yaml'), content: emptyYaml() },
    // environments/
    { path: p('environments/dev/.gitkeep'), content: EMPTY },
    { path: p('environments/staging/.gitkeep'), content: EMPTY },
    { path: p('environments/prod/.gitkeep'), content: EMPTY },
    // governance/
    { path: p('governance/approval-rules.yaml'), content: emptyYaml() },
    { path: p('governance/rbac.yaml'), content: emptyYaml() },
    { path: p('governance/resource-allocation.yaml'), content: emptyYaml() },
    // .github/workflows/
    { path: p('.github/workflows/ci.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/cross-domain-test.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/product-release.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/product-rollback.yaml'), content: emptyYaml() },
    // root files
    { path: p('OWNERS'), content: ownersFile(`${productName} Product Line`) },
    { path: p('README.md'), content: readmeFile(`${productName} 产品线`, '产品线入门指南。') },
  ];
}

// ─── §7.3 领域层 {domain}/ ────────────────────────────────────────────────

function buildDomain(domain: string, productName: string): ProductFileEntry[] {
  const p = (f: string) => `${domain}/${f}`;
  return [
    // docs/
    { path: p('docs/overview.md'), content: overviewMd(`${productName} 领域`, '领域概述：边界定义、管辖应用清单、上下游集成关系。') },
    { path: p('docs/VIEWS.yaml'), content: emptyYaml() },
    { path: p('docs/features/.gitkeep'), content: EMPTY },
    { path: p('docs/delivery/breakdown/app-status.yaml'), content: INDEX_YAML },
    { path: p('docs/journeys/.gitkeep'), content: EMPTY },
    { path: p('docs/strategy/roadmap.md'), content: roadmapMd(`${productName} 领域`) },
    { path: p('docs/strategy/okr.md'), content: knowledgeMd('领域 OKR') },
    { path: p('docs/qa/test-cases/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/qa/test-plans/.gitkeep'), content: EMPTY },
    { path: p('docs/qa/reports/_index.yaml'), content: INDEX_YAML },
    // knowledge/
    { path: p('knowledge/GLOSSARY.md'), content: knowledgeMd('域内统一语言词汇表') },
    { path: p('knowledge/context-map.md'), content: knowledgeMd('域内上下文地图') },
    { path: p('knowledge/domain-data-model.md'), content: knowledgeMd('域内共享数据模型') },
    { path: p('knowledge/integration-patterns.md'), content: knowledgeMd('域内集成规范') },
    { path: p('knowledge/shared-events.yaml'), content: emptyYaml() },
    { path: p('knowledge/scenarios/.gitkeep'), content: EMPTY },
    // registry/
    { path: p('registry/apps.yaml'), content: emptyYaml() },
    { path: p('registry/sdd-status.yaml'), content: emptyYaml() },
    { path: p('registry/delivery-status.yaml'), content: emptyYaml() },
    // environments/
    { path: p('environments/dev/env.yaml'), content: emptyYaml() },
    { path: p('environments/dev/overrides.yaml'), content: emptyYaml() },
    { path: p('environments/staging/.gitkeep'), content: EMPTY },
    { path: p('environments/prod/.gitkeep'), content: EMPTY },
    // .github/workflows/
    { path: p('.github/workflows/ci.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/domain-release.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/domain-rollback.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/integration-test.yaml'), content: emptyYaml() },
    // root files
    { path: p('OWNERS'), content: ownersFile(`${productName} Domain`) },
    { path: p('README.md'), content: readmeFile(`${productName} 领域`, '领域入门指南。') },
  ];
}

// ─── §7.4 应用层 apps/{app}/ ──────────────────────────────────────────────

function buildApp(app: string, productName: string): ProductFileEntry[] {
  const p = (f: string) => `apps/${app}/${f}`;
  return [
    // docs/
    { path: p('docs/overview.md'), content: overviewMd(`${app}`, '应用概述：功能边界、架构简图、外部依赖。') },
    { path: p('docs/VIEWS.yaml'), content: emptyYaml() },
    { path: p('docs/journeys/.gitkeep'), content: EMPTY },
    { path: p('docs/product/prd/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/product/architecture/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/product/contracts/openapi/.gitkeep'), content: EMPTY },
    { path: p('docs/product/contracts/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/roadmap.md'), content: roadmapMd(`${app} 应用`) },
    { path: p('docs/delivery/risk-register.md'), content: knowledgeMd('风险登记簿') },
    { path: p('docs/delivery/plan/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/task/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/releases/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/archive/.gitkeep'), content: EMPTY },
    { path: p('docs/features/.gitkeep'), content: EMPTY },
    { path: p('docs/ops/runbook/deployment.md'), content: knowledgeMd('部署运维手册') },
    { path: p('docs/ops/runbook/incident-response.md'), content: knowledgeMd('故障响应手册') },
    { path: p('docs/ops/runbook/monitoring.md'), content: knowledgeMd('监控手册') },
    // helm/
    { path: p('helm/Chart.yaml'), content: `apiVersion: v2\nname: ${app}\nversion: 0.1.0\nappVersion: "0.1.0"\n` },
    { path: p('helm/values/dev.yaml'), content: emptyYaml() },
    { path: p('helm/values/staging.yaml'), content: emptyYaml() },
    { path: p('helm/values/prod.yaml'), content: emptyYaml() },
    // .github/workflows/
    { path: p('.github/workflows/ci.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/cd.yaml'), content: emptyYaml() },
    // root files
    { path: p('orchestrator.yaml'), content: `# ${app} Pipeline Orchestrator\nmode: supervised\n` },
    { path: p('.githooks/commit-msg'), content: '#!/bin/sh\n# Enforce TASK reference in commit message\n' },
    { path: p('.pre-commit-config.yaml'), content: emptyYaml() },
    { path: p('docker-compose.yaml'), content: `# ${app} local dev environment\nversion: "3.8"\nservices: {}\n` },
    { path: p('.env.example'), content: `# ${app} environment variables\n` },
    { path: p('Makefile'), content: `# ${app} Makefile\n.PHONY: build test deploy\n\nbuild:\n\t@echo "build"\n\ntest:\n\t@echo "test"\n\ndeploy:\n\t@echo "deploy"\n` },
  ];
}

// ─── §8.3 Solo Monorepo 根目录 ────────────────────────────────────────────

function buildMonorepoRoot(productName: string): ProductFileEntry[] {
  return [
    { path: 'packages/shared-types/.gitkeep', content: EMPTY },
    { path: '.github/workflows/monorepo-orchestrator.yaml', content: emptyYaml() },
    { path: 'OWNERS', content: ownersFile(productName) },
    { path: 'README.md', content: readmeFile(productName, `${productName} Solo Monorepo`) },
  ];
}

// ─── 团队版入口（各子仓库独立路径） ───────────────────────────────────────

/**
 * 团队版产品线仓库根文件列表（路径相对于 {workDir}/{plSlug}/）
 * 内容与 Solo Monorepo 中的产品线层一致，但相对路径从仓库根开始
 */
export function buildTeamProductLineFiles(productName: string): ProductFileEntry[] {
  return [
    // docs/
    { path: 'docs/overview.md', content: overviewMd(`${productName} 产品线`, '产品线概述：背景、愿景、管辖领域、核心目标。') },
    { path: 'docs/VIEWS.yaml', content: emptyYaml() },
    { path: 'docs/features/.gitkeep', content: EMPTY },
    { path: 'docs/journeys/.gitkeep', content: EMPTY },
    { path: 'docs/help-center/guides/.gitkeep', content: EMPTY },
    { path: 'docs/help-center/faq/.gitkeep', content: EMPTY },
    { path: 'docs/help-center/troubleshooting/.gitkeep', content: EMPTY },
    { path: 'docs/help-center/release-notes/.gitkeep', content: EMPTY },
    { path: 'docs/help-center/_index.yaml', content: INDEX_YAML },
    { path: 'docs/delivery/roadmap.md', content: roadmapMd(`${productName} 产品线交付`) },
    { path: 'docs/delivery/breakdown/strategy-status.yaml', content: INDEX_YAML },
    // knowledge/
    { path: 'knowledge/GLOSSARY.md', content: knowledgeMd('跨域统一语言词汇表') },
    { path: 'knowledge/context-map.md', content: knowledgeMd('领域间边界地图') },
    { path: 'knowledge/data-model.md', content: knowledgeMd('跨域共享数据模型') },
    { path: 'knowledge/integration-patterns.md', content: knowledgeMd('跨域集成规范') },
    { path: 'knowledge/shared-events.yaml', content: emptyYaml() },
    { path: 'knowledge/scenarios/.gitkeep', content: EMPTY },
    { path: 'knowledge/adr/.gitkeep', content: EMPTY },
    // strategy/
    { path: 'strategy/roadmap.md', content: roadmapMd(`${productName} 战略`) },
    { path: 'strategy/prd/_index.yaml', content: INDEX_YAML },
    { path: 'strategy/gap-analysis/.gitkeep', content: EMPTY },
    { path: 'strategy/research/_index.yaml', content: INDEX_YAML },
    { path: 'strategy/research/archive/.gitkeep', content: EMPTY },
    // registry/
    { path: 'registry/domains.yaml', content: emptyYaml() },
    { path: 'registry/domain-status.yaml', content: emptyYaml() },
    { path: 'registry/strategy-status.yaml', content: emptyYaml() },
    // environments/
    { path: 'environments/dev/.gitkeep', content: EMPTY },
    { path: 'environments/staging/.gitkeep', content: EMPTY },
    { path: 'environments/prod/.gitkeep', content: EMPTY },
    // governance/
    { path: 'governance/approval-rules.yaml', content: emptyYaml() },
    { path: 'governance/rbac.yaml', content: emptyYaml() },
    { path: 'governance/resource-allocation.yaml', content: emptyYaml() },
    // .github/workflows/
    { path: '.github/workflows/ci.yaml', content: emptyYaml() },
    { path: '.github/workflows/cross-domain-test.yaml', content: emptyYaml() },
    { path: '.github/workflows/product-release.yaml', content: emptyYaml() },
    { path: '.github/workflows/product-rollback.yaml', content: emptyYaml() },
    // root files
    { path: 'OWNERS', content: ownersFile(`${productName} Product Line`) },
    { path: 'README.md', content: readmeFile(`${productName} 产品线`, '产品线入门指南。') },
  ];
}

/**
 * 团队版 Domain 仓库根文件列表（路径相对于 {workDir}/{domainSlug}/）
 */
export function buildTeamDomainFiles(domainName: string, productName: string): ProductFileEntry[] {
  return [
    // docs/
    { path: 'docs/overview.md', content: overviewMd(`${productName} ${domainName}`, '领域概述：边界定义、管辖应用清单、上下游集成关系。') },
    { path: 'docs/VIEWS.yaml', content: emptyYaml() },
    { path: 'docs/features/.gitkeep', content: EMPTY },
    { path: 'docs/delivery/breakdown/app-status.yaml', content: INDEX_YAML },
    { path: 'docs/journeys/.gitkeep', content: EMPTY },
    { path: 'docs/strategy/roadmap.md', content: roadmapMd(`${productName} ${domainName}`) },
    { path: 'docs/strategy/okr.md', content: knowledgeMd('领域 OKR') },
    { path: 'docs/qa/test-cases/_index.yaml', content: INDEX_YAML },
    { path: 'docs/qa/test-plans/.gitkeep', content: EMPTY },
    { path: 'docs/qa/reports/_index.yaml', content: INDEX_YAML },
    // knowledge/
    { path: 'knowledge/GLOSSARY.md', content: knowledgeMd('域内统一语言词汇表') },
    { path: 'knowledge/context-map.md', content: knowledgeMd('域内上下文地图') },
    { path: 'knowledge/domain-data-model.md', content: knowledgeMd('域内共享数据模型') },
    { path: 'knowledge/integration-patterns.md', content: knowledgeMd('域内集成规范') },
    { path: 'knowledge/shared-events.yaml', content: emptyYaml() },
    { path: 'knowledge/scenarios/.gitkeep', content: EMPTY },
    // registry/
    { path: 'registry/apps.yaml', content: emptyYaml() },
    { path: 'registry/sdd-status.yaml', content: emptyYaml() },
    { path: 'registry/delivery-status.yaml', content: emptyYaml() },
    // environments/
    { path: 'environments/dev/env.yaml', content: emptyYaml() },
    { path: 'environments/dev/overrides.yaml', content: emptyYaml() },
    { path: 'environments/staging/.gitkeep', content: EMPTY },
    { path: 'environments/prod/.gitkeep', content: EMPTY },
    // .github/workflows/
    { path: '.github/workflows/ci.yaml', content: emptyYaml() },
    { path: '.github/workflows/domain-release.yaml', content: emptyYaml() },
    { path: '.github/workflows/domain-rollback.yaml', content: emptyYaml() },
    { path: '.github/workflows/integration-test.yaml', content: emptyYaml() },
    // root files
    { path: 'OWNERS', content: ownersFile(`${productName} ${domainName} Domain`) },
    { path: 'README.md', content: readmeFile(`${productName} ${domainName}`, '领域入门指南。') },
  ];
}

/**
 * 团队版 App 仓库根文件列表（路径相对于 {workDir}/apps/{appSlug}/）
 */
export function buildTeamAppFiles(appName: string, productName: string): ProductFileEntry[] {
  return [
    // docs/
    { path: 'docs/overview.md', content: overviewMd(appName, '应用概述：功能边界、架构简图、外部依赖。') },
    { path: 'docs/VIEWS.yaml', content: emptyYaml() },
    { path: 'docs/journeys/.gitkeep', content: EMPTY },
    { path: 'docs/product/prd/_index.yaml', content: INDEX_YAML },
    { path: 'docs/product/architecture/_index.yaml', content: INDEX_YAML },
    { path: 'docs/product/contracts/openapi/.gitkeep', content: EMPTY },
    { path: 'docs/product/contracts/_index.yaml', content: INDEX_YAML },
    { path: 'docs/delivery/roadmap.md', content: roadmapMd(`${appName} 应用`) },
    { path: 'docs/delivery/risk-register.md', content: knowledgeMd('风险登记簿') },
    { path: 'docs/delivery/plan/_index.yaml', content: INDEX_YAML },
    { path: 'docs/delivery/task/_index.yaml', content: INDEX_YAML },
    { path: 'docs/delivery/releases/_index.yaml', content: INDEX_YAML },
    { path: 'docs/delivery/archive/.gitkeep', content: EMPTY },
    { path: 'docs/features/.gitkeep', content: EMPTY },
    { path: 'docs/ops/runbook/deployment.md', content: knowledgeMd('部署运维手册') },
    { path: 'docs/ops/runbook/incident-response.md', content: knowledgeMd('故障响应手册') },
    { path: 'docs/ops/runbook/monitoring.md', content: knowledgeMd('监控手册') },
    // helm/
    { path: 'helm/Chart.yaml', content: `apiVersion: v2\nname: ${appName}\nversion: 0.1.0\nappVersion: "0.1.0"\n` },
    { path: 'helm/values/dev.yaml', content: emptyYaml() },
    { path: 'helm/values/staging.yaml', content: emptyYaml() },
    { path: 'helm/values/prod.yaml', content: emptyYaml() },
    // .github/workflows/
    { path: '.github/workflows/ci.yaml', content: emptyYaml() },
    { path: '.github/workflows/cd.yaml', content: emptyYaml() },
    // root files
    { path: 'orchestrator.yaml', content: `# ${appName} Pipeline Orchestrator\nmode: supervised\n` },
    { path: '.githooks/commit-msg', content: '#!/bin/sh\n# Enforce TASK reference in commit message\n' },
    { path: '.pre-commit-config.yaml', content: emptyYaml() },
    { path: 'docker-compose.yaml', content: `# ${appName} local dev environment\nversion: "3.8"\nservices: {}\n` },
    { path: '.env.example', content: `# ${appName} environment variables\n` },
    { path: 'Makefile', content: `# ${appName} Makefile\n.PHONY: build test deploy\n\nbuild:\n\t@echo "build"\n\ntest:\n\t@echo "test"\n\ndeploy:\n\t@echo "deploy"\n` },
    { path: 'README.md', content: readmeFile(appName, `${productName} ${appName} 应用`) },
  ];
}

/**
 * 团队版父工作目录中的 .xingjing/config.yaml
 * 记录产品结构信息，作为多仓库的元数据入口
 */
export function buildTeamRootConfig(
  productName: string,
  plSlug: string,
  domainSlugs: string[],
  appSlugs: string[],
): ProductFileEntry[] {
  return [
    {
      path: '.xingjing/config.yaml',
      content: [
        `name: ${productName}`,
        `version: "1.0.0"`,
        `mode: team`,
        `created-at: ${new Date().toISOString()}`,
        `product-line: ${plSlug}`,
        `domains:`,
        ...domainSlugs.map(d => `  - ${d}`),
        `apps:`,
        ...appSlugs.map(a => `  - ${a}`),
        '',
      ].join('\n'),
    },
    // .xingjing/dir-graph.yaml（目录文档关系图谱，供 Agent 差异化解析）
    {
      path: '.xingjing/dir-graph.yaml',
      content: buildTeamDirGraph(
        { mode: 'team', pl: plSlug, domain: domainSlugs[0] ?? 'default-domain', app: appSlugs[0] ?? 'default-app' },
        domainSlugs,
        appSlugs,
      ),
    },
    // 知识规约文件（AGENTS.md + Agent + Skill）
    ...buildKnowledgeAgentFiles({ mode: 'team', pl: plSlug, domain: domainSlugs[0] ?? 'default-domain', app: appSlugs[0] ?? 'default-app' }),
  ];
}

// ─── 目录文档关系图谱 (.xingjing/dir-graph.yaml) ─────────────────────────────

/** 生成 Solo 模式的 dir-graph.yaml 内容 */
function buildSoloDirGraph(ctx: PathCtx): string {
  const { pl, domain, app } = ctx;
  const a = `apps/${app}`;
  const now = new Date().toISOString();
  return [
    `version: "1.0"`,
    `mode: solo`,
    `generated-at: "${now}"`,
    ``,
    `# ── 路径变量（Agent 解析时替换为实际值） ──`,
    `path-vars:`,
    `  pl: "${pl}"`,
    `  domain: "${domain}"`,
    `  app: "${a}"`,
    ``,
    `# ── 知识层级定义（Solo 四层） ──`,
    `layers:`,
    `  - id: platform`,
    `    name: 平台层`,
    `    path: governance-standards/`,
    `    description: 全公司共享规范（Schema、模板、质量门禁）`,
    `    contains: [schema, template, quality-gate, convention, capability]`,
    `  - id: product-line`,
    `    name: 产品线层（合并领域层）`,
    `    path: ${pl}/`,
    `    description: 产品知识，承担跨应用协调职责，合并产品线和领域层内容`,
    `    contains: [strategy-prd, glossary, context-map, shared-events, data-model, integration-patterns, scenario, journey, guide, faq, benchmark, market, customer]`,
    `  - id: domain`,
    `    name: 领域层（Solo 保留）`,
    `    path: ${domain}/`,
    `    description: 域内聚合知识（词汇、事件、上下文地图、测试用例）`,
    `    contains: [glossary, context-map, shared-events, domain-data-model, tc, tp, tr]`,
    `  - id: application`,
    `    name: 应用层`,
    `    path: ${a}/`,
    `    description: 应用自治知识（PRD/SDD/MODULE/PLAN/TASK/Runbook）`,
    `    contains: [prd, sdd, module, openapi, plan, task, release, runbook, journey, feature]`,
    `  - id: feature`,
    `    name: 特性层`,
    `    path: ${a}/docs/features/{feature}/`,
    `    description: 以特性为轴聚合文档，跨职能协作单元`,
    `    contains: [feature-readme, spec, plan, task]`,
    ``,
    `# ── 文档类型注册表 ──`,
    `doc-types:`,
    `  # --- 基线文档（原地更新） ---`,
    `  PRD:`,
    `    name: 产品需求文档`,
    `    category: baseline`,
    `    naming: "PRD-{NNN}-{name}.md"`,
    `    locations: ["${a}/docs/product/prd/"]`,
    `    owner: product-brain`,
    `    upstream: []`,
    `    downstream: [SDD]`,
    `    index: _index.yaml`,
    `  SDD:`,
    `    name: 系统设计文档`,
    `    category: baseline`,
    `    naming: "SDD-{NNN}-{name}.md"`,
    `    locations: ["${a}/docs/product/architecture/"]`,
    `    owner: eng-brain`,
    `    upstream: [PRD]`,
    `    downstream: [MODULE]`,
    `    index: _index.yaml`,
    `  MODULE:`,
    `    name: 接口规格文档`,
    `    category: baseline`,
    `    naming: "MODULE-{NNN}-{name}.md"`,
    `    locations: ["${a}/docs/product/contracts/"]`,
    `    owner: eng-brain`,
    `    upstream: [SDD]`,
    `    downstream: [PLAN]`,
    `    index: _index.yaml`,
    `  OpenAPI:`,
    `    name: OpenAPI 接口定义`,
    `    category: baseline`,
    `    naming: "{service}-{ver}.yaml"`,
    `    locations: ["${a}/docs/product/contracts/openapi/"]`,
    `    owner: eng-brain`,
    `    upstream: [MODULE]`,
    `    downstream: []`,
    `  JOURNEY:`,
    `    name: 用户旅程`,
    `    category: baseline`,
    `    naming: "JOURNEY-{NNN}-{name}.md"`,
    `    locations: ["${a}/docs/journeys/", "${pl}/docs/journeys/"]`,
    `    owner: product-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  SCENARIO:`,
    `    name: 业务场景`,
    `    category: baseline`,
    `    naming: "SCENARIO-{NNN}-{name}.md"`,
    `    locations: ["${pl}/knowledge/scenarios/"]`,
    `    owner: product-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  GUIDE:`,
    `    name: 操作指南`,
    `    category: baseline`,
    `    naming: "GUIDE-{NNN}-{name}.md"`,
    `    locations: ["${pl}/docs/help-center/guides/"]`,
    `    owner: product-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  FAQ:`,
    `    name: 常见问题`,
    `    category: baseline`,
    `    naming: "FAQ-{topic}.md"`,
    `    locations: ["${pl}/docs/help-center/faq/"]`,
    `    owner: growth-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  Runbook:`,
    `    name: 运维手册`,
    `    category: baseline`,
    `    naming: "{type}.md"`,
    `    locations: ["${a}/docs/ops/runbook/"]`,
    `    owner: ops-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  GLOSSARY:`,
    `    name: 统一语言词汇表`,
    `    category: baseline`,
    `    naming: "GLOSSARY.md"`,
    `    locations: ["${pl}/knowledge/", "${domain}/knowledge/"]`,
    `    owner: eng-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  # --- 过程文档（交付类，按版本归档） ---`,
    `  PLAN:`,
    `    name: 迭代计划`,
    `    category: process-delivery`,
    `    naming: "PLAN-{VER}-{NNN}-{name}.md"`,
    `    locations: ["${a}/docs/delivery/plan/"]`,
    `    owner: eng-brain`,
    `    upstream: [MODULE]`,
    `    downstream: [TASK]`,
    `    index: _index.yaml`,
    `  TASK:`,
    `    name: 开发任务卡`,
    `    category: process-delivery`,
    `    naming: "TASK-{VER}-{NNN}-{NN}-{name}.md"`,
    `    locations: ["${a}/docs/delivery/task/"]`,
    `    owner: eng-brain`,
    `    upstream: [PLAN]`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  RELEASE:`,
    `    name: 发版计划`,
    `    category: process-delivery`,
    `    naming: "RELEASE-{version}.md"`,
    `    locations: ["${a}/docs/delivery/releases/"]`,
    `    owner: ops-brain`,
    `    upstream: [PLAN]`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  TR:`,
    `    name: 测试报告`,
    `    category: process-delivery`,
    `    naming: "TR-{VER}-{NNN}-{name}.md"`,
    `    locations: ["${domain}/docs/qa/reports/"]`,
    `    owner: ops-brain`,
    `    upstream: [PLAN]`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  TC:`,
    `    name: 测试用例`,
    `    category: process-delivery`,
    `    naming: "TC-{NNN}-{name}.md"`,
    `    locations: ["${domain}/docs/qa/test-cases/"]`,
    `    owner: eng-brain`,
    `    upstream: [MODULE]`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  # --- 过程文档（研究类，按季度归档） ---`,
    `  BENCHMARK:`,
    `    name: 竞品分析报告`,
    `    category: process-research`,
    `    naming: "BENCHMARK-{YYYYQN}-{NNN}-{name}.md"`,
    `    locations: ["${pl}/strategy/research/"]`,
    `    owner: growth-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  MARKET:`,
    `    name: 市场分析报告`,
    `    category: process-research`,
    `    naming: "MARKET-{YYYYQN}-{NNN}-{name}.md"`,
    `    locations: ["${pl}/strategy/research/"]`,
    `    owner: growth-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  CUSTOMER:`,
    `    name: 客户洞察报告`,
    `    category: process-research`,
    `    naming: "CUSTOMER-{YYYYQN}-{NNN}-{name}.md"`,
    `    locations: ["${pl}/strategy/research/"]`,
    `    owner: growth-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  GAP:`,
    `    name: 差距分析报告`,
    `    category: process-research`,
    `    naming: "GAP-{YYYYQN}-{NNN}-{name}.md"`,
    `    locations: ["${pl}/strategy/gap-analysis/"]`,
    `    owner: growth-brain`,
    `    upstream: []`,
    `    downstream: []`,
    ``,
    `# ── 文档链路（上游 approved 才能创建下游） ──`,
    `doc-chain:`,
    `  - { from: PRD, to: SDD, gate: "PRD.status == approved" }`,
    `  - { from: SDD, to: MODULE, gate: "SDD.status == approved" }`,
    `  - { from: MODULE, to: PLAN, gate: "MODULE.status == approved" }`,
    `  - { from: PLAN, to: TASK, gate: "PLAN.status == approved" }`,
    ``,
    `# ── Agent 产出映射 ──`,
    `agents:`,
    `  product-brain:`,
    `    name: AI产品搭档`,
    `    outputs:`,
    `      - { type: PRD, path: "${a}/docs/product/prd/" }`,
    `      - { type: strategy-prd, path: "${pl}/strategy/prd/" }`,
    `      - { type: JOURNEY, path: "${a}/docs/journeys/" }`,
    `      - { type: SCENARIO, path: "${pl}/knowledge/scenarios/" }`,
    `      - { type: GUIDE, path: "${pl}/docs/help-center/guides/" }`,
    `      - { type: Roadmap, path: "${a}/docs/delivery/roadmap.md" }`,
    `  eng-brain:`,
    `    name: AI工程搭档`,
    `    outputs:`,
    `      - { type: SDD, path: "${a}/docs/product/architecture/" }`,
    `      - { type: MODULE, path: "${a}/docs/product/contracts/" }`,
    `      - { type: OpenAPI, path: "${a}/docs/product/contracts/openapi/" }`,
    `      - { type: PLAN, path: "${a}/docs/delivery/plan/" }`,
    `      - { type: TASK, path: "${a}/docs/delivery/task/" }`,
    `      - { type: TC, path: "${domain}/docs/qa/test-cases/" }`,
    `      - { type: Helm, path: "${a}/helm/values/" }`,
    `  growth-brain:`,
    `    name: AI增长搭档`,
    `    outputs:`,
    `      - { type: BENCHMARK, path: "${pl}/strategy/research/" }`,
    `      - { type: MARKET, path: "${pl}/strategy/research/" }`,
    `      - { type: CUSTOMER, path: "${pl}/strategy/research/" }`,
    `      - { type: GUIDE, path: "${pl}/docs/help-center/guides/" }`,
    `      - { type: FAQ, path: "${pl}/docs/help-center/faq/" }`,
    `      - { type: RN, path: "${pl}/docs/help-center/release-notes/" }`,
    `      - { type: GAP, path: "${pl}/strategy/gap-analysis/" }`,
    `  ops-brain:`,
    `    name: AI运营搭档`,
    `    outputs:`,
    `      - { type: Runbook, path: "${a}/docs/ops/runbook/" }`,
    `      - { type: RELEASE, path: "${a}/docs/delivery/releases/" }`,
    `      - { type: TR, path: "${domain}/docs/qa/reports/" }`,
    `      - { type: risk-register, path: "${a}/docs/delivery/risk-register.md" }`,
    ``,
  ].join('\n');
}

/** 生成 Team 模式的 dir-graph.yaml 内容 */
function buildTeamDirGraph(
  ctx: PathCtx,
  domainSlugs: string[],
  appSlugs: string[],
): string {
  const { pl } = ctx;
  const now = new Date().toISOString();
  // Team 模式取第一个 domain 和 app 作为主引用路径
  const primaryDomain = domainSlugs[0] ?? 'default-domain';
  const primaryApp = `apps/${appSlugs[0] ?? 'default-app'}`;
  return [
    `version: "1.0"`,
    `mode: team`,
    `generated-at: "${now}"`,
    ``,
    `# ── 路径变量（Agent 解析时替换为实际值） ──`,
    `path-vars:`,
    `  pl: "${pl}"`,
    `  domains:`,
    ...domainSlugs.map(d => `    - "${d}"`),
    `  apps:`,
    ...appSlugs.map(a => `    - "apps/${a}"`),
    ``,
    `# ── 知识层级定义（Team 六层） ──`,
    `layers:`,
    `  - id: platform`,
    `    name: 平台层`,
    `    path: governance-standards/`,
    `    description: 全公司共享规范（Schema、模板、质量门禁）`,
    `    contains: [schema, template, quality-gate, convention, capability]`,
    `  - id: product-line`,
    `    name: 产品线层`,
    `    path: ${pl}/`,
    `    description: 跨领域知识、战略PRD、帮助中心`,
    `    contains: [strategy-prd, glossary, context-map, shared-events, data-model, integration-patterns, scenario, journey, guide, faq, benchmark, market, customer]`,
    `  - id: domain`,
    `    name: 领域层`,
    `    paths:`,
    ...domainSlugs.map(d => `      - ${d}/`),
    `    description: 域内聚合知识（词汇、事件、上下文地图、测试用例）`,
    `    contains: [glossary, context-map, shared-events, domain-data-model, tc, tp, tr]`,
    `  - id: application`,
    `    name: 应用层`,
    `    paths:`,
    ...appSlugs.map(a => `      - apps/${a}/`),
    `    description: 应用自治知识（PRD/SDD/MODULE/PLAN/TASK/Runbook）`,
    `    contains: [prd, sdd, module, openapi, plan, task, release, runbook, journey, feature]`,
    `  - id: feature`,
    `    name: 特性层`,
    `    path: "{app}/docs/features/{feature}/"`,
    `    description: 以特性为轴聚合文档，跨职能协作单元`,
    `    contains: [feature-readme, spec, plan, task, form]`,
    `  - id: form`,
    `    name: 表单层（DDD 最小颗粒度）`,
    `    path: "{app}/docs/features/{feature}/forms/{form}/"`,
    `    description: 对应 DDD 聚合根，承载字段定义、验证规则和业务约束`,
    `    contains: [form-spec, schema, tc-form]`,
    ``,
    `# ── 文档类型注册表 ──`,
    `doc-types:`,
    `  # --- 基线文档（原地更新） ---`,
    `  PRD:`,
    `    name: 产品需求文档`,
    `    category: baseline`,
    `    naming: "PRD-{NNN}-{name}.md"`,
    `    locations: ["{app}/docs/product/prd/"]`,
    `    owner: product-brain`,
    `    upstream: []`,
    `    downstream: [SDD]`,
    `    index: _index.yaml`,
    `  SDD:`,
    `    name: 系统设计文档`,
    `    category: baseline`,
    `    naming: "SDD-{NNN}-{name}.md"`,
    `    locations: ["{app}/docs/product/architecture/"]`,
    `    owner: eng-brain`,
    `    upstream: [PRD]`,
    `    downstream: [MODULE]`,
    `    index: _index.yaml`,
    `  MODULE:`,
    `    name: 接口规格文档`,
    `    category: baseline`,
    `    naming: "MODULE-{NNN}-{name}.md"`,
    `    locations: ["{app}/docs/product/contracts/"]`,
    `    owner: eng-brain`,
    `    upstream: [SDD]`,
    `    downstream: [PLAN]`,
    `    index: _index.yaml`,
    `  OpenAPI:`,
    `    name: OpenAPI 接口定义`,
    `    category: baseline`,
    `    naming: "{service}-{ver}.yaml"`,
    `    locations: ["{app}/docs/product/contracts/openapi/"]`,
    `    owner: eng-brain`,
    `    upstream: [MODULE]`,
    `    downstream: []`,
    `  FORM:`,
    `    name: 表单规格（DDD 聚合根）`,
    `    category: baseline`,
    `    naming: "FORM-{NNN}-{name}.md"`,
    `    locations: ["{app}/docs/features/{feature}/forms/{form}/"]`,
    `    owner: eng-brain`,
    `    upstream: [PRD, MODULE]`,
    `    downstream: []`,
    `  form-schema:`,
    `    name: 表单数据结构`,
    `    category: baseline`,
    `    naming: "schema.yaml"`,
    `    locations: ["{app}/docs/features/{feature}/forms/{form}/"]`,
    `    owner: eng-brain`,
    `    upstream: [FORM]`,
    `    downstream: []`,
    `  TC-FORM:`,
    `    name: 表单测试用例`,
    `    category: baseline`,
    `    naming: "TC-FORM-{NNN}-{name}.md"`,
    `    locations: ["{app}/docs/features/{feature}/forms/{form}/test-cases/"]`,
    `    owner: eng-brain`,
    `    upstream: [FORM]`,
    `    downstream: []`,
    `  JOURNEY:`,
    `    name: 用户旅程`,
    `    category: baseline`,
    `    naming: "JOURNEY-{NNN}-{name}.md"`,
    `    locations: ["{app}/docs/journeys/", "${pl}/docs/journeys/", "{domain}/docs/journeys/"]`,
    `    owner: product-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  SCENARIO:`,
    `    name: 业务场景`,
    `    category: baseline`,
    `    naming: "SCENARIO-{NNN}-{name}.md"`,
    `    locations: ["${pl}/knowledge/scenarios/", "{domain}/knowledge/scenarios/"]`,
    `    owner: product-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  GUIDE:`,
    `    name: 操作指南`,
    `    category: baseline`,
    `    naming: "GUIDE-{NNN}-{name}.md"`,
    `    locations: ["${pl}/docs/help-center/guides/"]`,
    `    owner: product-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  FAQ:`,
    `    name: 常见问题`,
    `    category: baseline`,
    `    naming: "FAQ-{topic}.md"`,
    `    locations: ["${pl}/docs/help-center/faq/"]`,
    `    owner: growth-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  Runbook:`,
    `    name: 运维手册`,
    `    category: baseline`,
    `    naming: "{type}.md"`,
    `    locations: ["{app}/docs/ops/runbook/"]`,
    `    owner: ops-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  GLOSSARY:`,
    `    name: 统一语言词汇表`,
    `    category: baseline`,
    `    naming: "GLOSSARY.md"`,
    `    locations: ["${pl}/knowledge/", "{domain}/knowledge/"]`,
    `    owner: eng-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `  # --- 过程文档（交付类，按版本归档） ---`,
    `  PLAN:`,
    `    name: 迭代计划`,
    `    category: process-delivery`,
    `    naming: "PLAN-{VER}-{NNN}-{name}.md"`,
    `    locations: ["{app}/docs/delivery/plan/"]`,
    `    owner: eng-brain`,
    `    upstream: [MODULE]`,
    `    downstream: [TASK]`,
    `    index: _index.yaml`,
    `  TASK:`,
    `    name: 开发任务卡`,
    `    category: process-delivery`,
    `    naming: "TASK-{VER}-{NNN}-{NN}-{name}.md"`,
    `    locations: ["{app}/docs/delivery/task/"]`,
    `    owner: eng-brain`,
    `    upstream: [PLAN]`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  RELEASE:`,
    `    name: 发版计划`,
    `    category: process-delivery`,
    `    naming: "RELEASE-{version}.md"`,
    `    locations: ["{app}/docs/delivery/releases/"]`,
    `    owner: ops-brain`,
    `    upstream: [PLAN]`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  TR:`,
    `    name: 测试报告`,
    `    category: process-delivery`,
    `    naming: "TR-{VER}-{NNN}-{name}.md"`,
    `    locations: ["{domain}/docs/qa/reports/"]`,
    `    owner: ops-brain`,
    `    upstream: [PLAN]`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  TC:`,
    `    name: 测试用例`,
    `    category: process-delivery`,
    `    naming: "TC-{NNN}-{name}.md"`,
    `    locations: ["{domain}/docs/qa/test-cases/"]`,
    `    owner: eng-brain`,
    `    upstream: [MODULE]`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  # --- 过程文档（研究类，按季度归档） ---`,
    `  BENCHMARK:`,
    `    name: 竞品分析报告`,
    `    category: process-research`,
    `    naming: "BENCHMARK-{YYYYQN}-{NNN}-{name}.md"`,
    `    locations: ["${pl}/strategy/research/"]`,
    `    owner: growth-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  MARKET:`,
    `    name: 市场分析报告`,
    `    category: process-research`,
    `    naming: "MARKET-{YYYYQN}-{NNN}-{name}.md"`,
    `    locations: ["${pl}/strategy/research/"]`,
    `    owner: growth-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  CUSTOMER:`,
    `    name: 客户洞察报告`,
    `    category: process-research`,
    `    naming: "CUSTOMER-{YYYYQN}-{NNN}-{name}.md"`,
    `    locations: ["${pl}/strategy/research/"]`,
    `    owner: growth-brain`,
    `    upstream: []`,
    `    downstream: []`,
    `    index: _index.yaml`,
    `  GAP:`,
    `    name: 差距分析报告`,
    `    category: process-research`,
    `    naming: "GAP-{YYYYQN}-{NNN}-{name}.md"`,
    `    locations: ["${pl}/strategy/gap-analysis/"]`,
    `    owner: growth-brain`,
    `    upstream: []`,
    `    downstream: []`,
    ``,
    `# ── 文档链路（上游 approved 才能创建下游） ──`,
    `doc-chain:`,
    `  - { from: PRD, to: SDD, gate: "PRD.status == approved" }`,
    `  - { from: SDD, to: MODULE, gate: "SDD.status == approved" }`,
    `  - { from: MODULE, to: PLAN, gate: "MODULE.status == approved" }`,
    `  - { from: PLAN, to: TASK, gate: "PLAN.status == approved" }`,
    `  - { from: PRD, to: FORM, gate: "PRD.status == approved" }`,
    `  - { from: MODULE, to: FORM, gate: "MODULE.status == approved" }`,
    ``,
    `# ── Agent 产出映射 ──`,
    `agents:`,
    `  product-brain:`,
    `    name: AI产品搭档`,
    `    outputs:`,
    `      - { type: PRD, path: "{app}/docs/product/prd/" }`,
    `      - { type: strategy-prd, path: "${pl}/strategy/prd/" }`,
    `      - { type: JOURNEY, path: "{app}/docs/journeys/" }`,
    `      - { type: SCENARIO, path: "${pl}/knowledge/scenarios/" }`,
    `      - { type: GUIDE, path: "${pl}/docs/help-center/guides/" }`,
    `      - { type: Roadmap, path: "{app}/docs/delivery/roadmap.md" }`,
    `  eng-brain:`,
    `    name: AI工程搭档`,
    `    outputs:`,
    `      - { type: SDD, path: "{app}/docs/product/architecture/" }`,
    `      - { type: MODULE, path: "{app}/docs/product/contracts/" }`,
    `      - { type: OpenAPI, path: "{app}/docs/product/contracts/openapi/" }`,
    `      - { type: FORM, path: "{app}/docs/features/{feat}/forms/{form}/" }`,
    `      - { type: form-schema, path: "{app}/docs/features/{feat}/forms/{form}/" }`,
    `      - { type: PLAN, path: "{app}/docs/delivery/plan/" }`,
    `      - { type: TASK, path: "{app}/docs/delivery/task/" }`,
    `      - { type: TC, path: "{domain}/docs/qa/test-cases/" }`,
    `      - { type: Helm, path: "{app}/helm/values/" }`,
    `  growth-brain:`,
    `    name: AI增长搭档`,
    `    outputs:`,
    `      - { type: BENCHMARK, path: "${pl}/strategy/research/" }`,
    `      - { type: MARKET, path: "${pl}/strategy/research/" }`,
    `      - { type: CUSTOMER, path: "${pl}/strategy/research/" }`,
    `      - { type: GUIDE, path: "${pl}/docs/help-center/guides/" }`,
    `      - { type: FAQ, path: "${pl}/docs/help-center/faq/" }`,
    `      - { type: RN, path: "${pl}/docs/help-center/release-notes/" }`,
    `      - { type: GAP, path: "${pl}/strategy/gap-analysis/" }`,
    `  ops-brain:`,
    `    name: AI运营搭档`,
    `    outputs:`,
    `      - { type: Runbook, path: "{app}/docs/ops/runbook/" }`,
    `      - { type: RELEASE, path: "{app}/docs/delivery/releases/" }`,
    `      - { type: TR, path: "{domain}/docs/qa/reports/" }`,
    `      - { type: risk-register, path: "{app}/docs/delivery/risk-register.md" }`,
    ``,
  ].join('\n');
}

// ─── 主入口 ───────────────────────────────────────────────────────────────

/**
 * 根据产品名、首个应用名及编码，生成完整的 Solo Monorepo 文件清单
 * @param productName 产品名（原始输入，用于文档内容）
 * @param appName     首个应用名（原始输入，用于文档内容）
 * @param productCode 产品英文编码，直接用作产品线目录名（{productCode}-pl）和 Domain 目录名（{productCode}-domain）
 * @param appCode     应用英文编码，直接用作 App 目录名
 * @returns 文件清单（path 相对于 workDir）
 */
export function buildProductFileList(
  productName: string,
  appName: string,
  productCode: string,
  appCode: string,
): ProductFileEntry[] {
  const pl = `${productCode}-pl`;
  const app = appCode;

  return [
    // .xingjing/config.yaml（星静自身配置）
    {
      path: '.xingjing/config.yaml',
      content: [
        `name: ${productName}`,
        `version: "1.0.0"`,
        `created-at: ${new Date().toISOString()}`,
        `product-line: ${pl}`,
        `apps:`,
        `  - ${app}`,
        '',
      ].join('\n'),
    },
    // .xingjing/dir-graph.yaml（目录文档关系图谱，供 Agent 差异化解析）
    { path: '.xingjing/dir-graph.yaml', content: buildSoloDirGraph({ mode: 'solo', pl, domain: `${productCode}-domain`, app }) },
    // .xingjing/solo/ 子目录（Solo 模式数据存储）
    { path: '.xingjing/solo/focus.yaml', content: 'items: []\n' },
    { path: '.xingjing/solo/metrics.yaml', content: 'businessMetrics: []\nmetricsHistory: []\nfeatureUsage: []\n' },
    { path: '.xingjing/solo/competitors.yaml', content: 'items: []\n' },
    { path: '.xingjing/solo/feature-flags.yaml', content: 'flags: []\n' },
    { path: '.xingjing/solo/hypotheses/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/feature-ideas/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/adrs/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/releases/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/knowledge/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/feedbacks/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/tasks/.gitkeep', content: EMPTY },
    // .opencode/agents/ + .opencode/skills/ + AGENTS.md — 知识规约文件
    ...buildKnowledgeAgentFiles({ mode: 'solo', pl, domain: `${productCode}-domain`, app }),
    // §8.3 根目录
    ...buildMonorepoRoot(productName),
    // §7.1 平台层
    ...buildGovernanceStandards(),
    // §7.2 产品线层
    ...buildProductLine(pl, productName),
    // §7.4 应用层
    ...buildApp(app, productName),
  ];
}
