/**
 * 产品目录结构定义（Solo Monorepo）
 *
 * 严格对照 KNOWLEDGE-LIFECYCLE.md §7.1-7.4 + §8.3
 * 导出 buildProductFileList(productName, appName) 生成完整文件清单
 */

// ─── 工具函数 ────────────────────────────────────────────────────────────────

/** 将任意字符串转为 kebab-case */
function toKebabCase(str: string): string {
  return str
    .trim()
    .replace(/[\s_]+/g, '-')
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9\u4e00-\u9fff-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

/** 生成 Agent 定义 .md 文件内容（frontmatter + 描述）*/
function agentMdContent(
  id: string, name: string, emoji: string,
  color: string, bgColor: string, borderColor: string,
  skills: string[], desc: string,
): string {
  return [
    '---', `id: ${id}`, `name: ${name}`, `role: ${name}`,
    `emoji: "${emoji}"`, `color: "${color}"`, `bgColor: "${bgColor}"`, `borderColor: "${borderColor}"`,
    'skills:', ...skills.map(s => `  - ${s}`), '---', desc, '',
  ].join('\n');
}

// ─── 文件条目类型 ─────────────────────────────────────────────────────────────

export interface ProductFileEntry {
  /** 相对于 workDir 的路径 */
  path: string;
  /** 文件初始内容 */
  content: string;
}

// ─── 内容生成辅助函数 ─────────────────────────────────────────────────────────

const EMPTY = '';
const INDEX_YAML = 'items: []\n';

function mdFrontmatter(meta: Record<string, string>): string {
  const lines = Object.entries(meta).map(([k, v]) => `${k}: ${v}`);
  return `---\n${lines.join('\n')}\n---\n\n`;
}

function overviewMd(title: string, description: string): string {
  return mdFrontmatter({ title, lifecycle: 'living', 'created-at': new Date().toISOString().slice(0, 10) })
    + `# ${title}\n\n${description}\n`;
}

function knowledgeMd(title: string): string {
  return mdFrontmatter({ title, lifecycle: 'living', 'created-at': new Date().toISOString().slice(0, 10) })
    + `# ${title}\n`;
}

function roadmapMd(scope: string): string {
  return mdFrontmatter({ title: `${scope} Roadmap`, lifecycle: 'living', 'created-at': new Date().toISOString().slice(0, 10) })
    + `# ${scope} Roadmap\n\n## Milestones\n\n_TODO_\n`;
}

function emptyYaml(): string {
  return '# Auto-generated by xingjing\n';
}

function ownersFile(name: string): string {
  return `# ${name}\n# Add owner GitHub handles below\n`;
}

function readmeFile(title: string, description: string): string {
  return `# ${title}\n\n${description}\n`;
}

// ─── §7.1 平台层 governance-standards/ ─────────────────────────────────────

function buildGovernanceStandards(): ProductFileEntry[] {
  const p = (f: string) => `governance-standards/${f}`;
  return [
    // schemas/
    { path: p('schemas/prd-schema.json'), content: '{}' },
    { path: p('schemas/sdd-schema.json'), content: '{}' },
    { path: p('schemas/contract-schema.json'), content: '{}' },
    { path: p('schemas/plan-schema.json'), content: '{}' },
    { path: p('schemas/strategy-prd-schema.json'), content: '{}' },
    { path: p('schemas/benchmark-schema.json'), content: '{}' },
    // templates/
    { path: p('templates/PRD-template.md'), content: '# PRD Template\n' },
    { path: p('templates/SDD-template.md'), content: '# SDD Template\n' },
    { path: p('templates/CONTRACT-template.md'), content: '# CONTRACT Template\n' },
    { path: p('templates/PLAN-template.md'), content: '# PLAN Template\n' },
    { path: p('templates/TASK-template.md'), content: '# TASK Template\n' },
    { path: p('templates/STRATEGY-PRD-template.md'), content: '# Strategy PRD Template\n' },
    { path: p('templates/BENCHMARK-template.md'), content: '# BENCHMARK Template\n' },
    { path: p('templates/FEATURE-template.md'), content: '# FEATURE Template\n' },
    { path: p('templates/RUNBOOK-template.md'), content: '# RUNBOOK Template\n' },
    { path: p('templates/ROADMAP-template.md'), content: '# ROADMAP Template\n' },
    { path: p('templates/PIPELINE-template.yaml'), content: emptyYaml() },
    { path: p('templates/_index-template.yaml'), content: INDEX_YAML },
    { path: p('templates/platform-adapters/.gitkeep'), content: EMPTY },
    { path: p('templates/scaffold/.gitkeep'), content: EMPTY },
    // quality-gates/
    { path: p('quality-gates/sdd-completeness.yaml'), content: emptyYaml() },
    { path: p('quality-gates/ci-gates.yaml'), content: emptyYaml() },
    { path: p('quality-gates/security-compliance.yaml'), content: emptyYaml() },
    { path: p('quality-gates/engineering-metrics.yaml'), content: emptyYaml() },
    // conventions/
    { path: p('conventions/naming.yaml'), content: emptyYaml() },
    { path: p('conventions/versioning.yaml'), content: emptyYaml() },
    { path: p('conventions/branching.yaml'), content: emptyYaml() },
    // capabilities/
    { path: p('capabilities/agents/.gitkeep'), content: EMPTY },
    { path: p('capabilities/skills/.gitkeep'), content: EMPTY },
    { path: p('capabilities/platform-overlays/.gitkeep'), content: EMPTY },
    { path: p('capabilities/registry.yaml'), content: emptyYaml() },
  ];
}

// ─── §7.2 产品线层 {pl}/ ──────────────────────────────────────────────────

function buildProductLine(pl: string, productName: string): ProductFileEntry[] {
  const p = (f: string) => `${pl}/${f}`;
  return [
    // docs/
    { path: p('docs/overview.md'), content: overviewMd(`${productName} 产品线`, '产品线概述：背景、愿景、管辖领域、核心目标。') },
    { path: p('docs/VIEWS.yaml'), content: emptyYaml() },
    { path: p('docs/features/.gitkeep'), content: EMPTY },
    { path: p('docs/journeys/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/guides/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/faq/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/troubleshooting/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/release-notes/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/roadmap.md'), content: roadmapMd(`${productName} 产品线交付`) },
    { path: p('docs/delivery/breakdown/strategy-status.yaml'), content: INDEX_YAML },
    // knowledge/
    { path: p('knowledge/GLOSSARY.md'), content: knowledgeMd('跨域统一语言词汇表') },
    { path: p('knowledge/context-map.md'), content: knowledgeMd('领域间边界地图') },
    { path: p('knowledge/data-model.md'), content: knowledgeMd('跨域共享数据模型') },
    { path: p('knowledge/integration-patterns.md'), content: knowledgeMd('跨域集成规范') },
    { path: p('knowledge/shared-events.yaml'), content: emptyYaml() },
    { path: p('knowledge/scenarios/.gitkeep'), content: EMPTY },
    { path: p('knowledge/adr/.gitkeep'), content: EMPTY },
    // strategy/
    { path: p('strategy/roadmap.md'), content: roadmapMd(`${productName} 战略`) },
    { path: p('strategy/prd/_index.yaml'), content: INDEX_YAML },
    { path: p('strategy/gap-analysis/.gitkeep'), content: EMPTY },
    { path: p('strategy/research/_index.yaml'), content: INDEX_YAML },
    { path: p('strategy/research/archive/.gitkeep'), content: EMPTY },
    // registry/
    { path: p('registry/domains.yaml'), content: emptyYaml() },
    { path: p('registry/domain-status.yaml'), content: emptyYaml() },
    { path: p('registry/strategy-status.yaml'), content: emptyYaml() },
    // environments/
    { path: p('environments/dev/.gitkeep'), content: EMPTY },
    { path: p('environments/staging/.gitkeep'), content: EMPTY },
    { path: p('environments/prod/.gitkeep'), content: EMPTY },
    // governance/
    { path: p('governance/approval-rules.yaml'), content: emptyYaml() },
    { path: p('governance/rbac.yaml'), content: emptyYaml() },
    { path: p('governance/resource-allocation.yaml'), content: emptyYaml() },
    // .github/workflows/
    { path: p('.github/workflows/ci.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/cross-domain-test.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/product-release.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/product-rollback.yaml'), content: emptyYaml() },
    // root files
    { path: p('OWNERS'), content: ownersFile(`${productName} Product Line`) },
    { path: p('README.md'), content: readmeFile(`${productName} 产品线`, '产品线入门指南。') },
  ];
}

// ─── §7.3 领域层 {domain}/ ────────────────────────────────────────────────

function buildDomain(domain: string, productName: string): ProductFileEntry[] {
  const p = (f: string) => `${domain}/${f}`;
  return [
    // docs/
    { path: p('docs/overview.md'), content: overviewMd(`${productName} 领域`, '领域概述：边界定义、管辖应用清单、上下游集成关系。') },
    { path: p('docs/VIEWS.yaml'), content: emptyYaml() },
    { path: p('docs/features/.gitkeep'), content: EMPTY },
    { path: p('docs/delivery/breakdown/app-status.yaml'), content: INDEX_YAML },
    { path: p('docs/journeys/.gitkeep'), content: EMPTY },
    { path: p('docs/strategy/roadmap.md'), content: roadmapMd(`${productName} 领域`) },
    { path: p('docs/strategy/okr.md'), content: knowledgeMd('领域 OKR') },
    { path: p('docs/qa/test-cases/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/qa/test-plans/.gitkeep'), content: EMPTY },
    { path: p('docs/qa/reports/_index.yaml'), content: INDEX_YAML },
    // knowledge/
    { path: p('knowledge/GLOSSARY.md'), content: knowledgeMd('域内统一语言词汇表') },
    { path: p('knowledge/context-map.md'), content: knowledgeMd('域内上下文地图') },
    { path: p('knowledge/domain-data-model.md'), content: knowledgeMd('域内共享数据模型') },
    { path: p('knowledge/integration-patterns.md'), content: knowledgeMd('域内集成规范') },
    { path: p('knowledge/shared-events.yaml'), content: emptyYaml() },
    { path: p('knowledge/scenarios/.gitkeep'), content: EMPTY },
    // registry/
    { path: p('registry/apps.yaml'), content: emptyYaml() },
    { path: p('registry/sdd-status.yaml'), content: emptyYaml() },
    { path: p('registry/delivery-status.yaml'), content: emptyYaml() },
    // environments/
    { path: p('environments/dev/env.yaml'), content: emptyYaml() },
    { path: p('environments/dev/overrides.yaml'), content: emptyYaml() },
    { path: p('environments/staging/.gitkeep'), content: EMPTY },
    { path: p('environments/prod/.gitkeep'), content: EMPTY },
    // .github/workflows/
    { path: p('.github/workflows/ci.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/domain-release.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/domain-rollback.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/integration-test.yaml'), content: emptyYaml() },
    // root files
    { path: p('OWNERS'), content: ownersFile(`${productName} Domain`) },
    { path: p('README.md'), content: readmeFile(`${productName} 领域`, '领域入门指南。') },
  ];
}

// ─── §7.4 应用层 apps/{app}/ ──────────────────────────────────────────────

function buildApp(app: string, productName: string): ProductFileEntry[] {
  const p = (f: string) => `apps/${app}/${f}`;
  return [
    // docs/
    { path: p('docs/overview.md'), content: overviewMd(`${app}`, '应用概述：功能边界、架构简图、外部依赖。') },
    { path: p('docs/VIEWS.yaml'), content: emptyYaml() },
    { path: p('docs/journeys/.gitkeep'), content: EMPTY },
    { path: p('docs/product/prd/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/product/architecture/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/product/contracts/openapi/.gitkeep'), content: EMPTY },
    { path: p('docs/product/contracts/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/roadmap.md'), content: roadmapMd(`${app} 应用`) },
    { path: p('docs/delivery/risk-register.md'), content: knowledgeMd('风险登记簿') },
    { path: p('docs/delivery/plan/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/task/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/releases/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/archive/.gitkeep'), content: EMPTY },
    { path: p('docs/features/.gitkeep'), content: EMPTY },
    { path: p('docs/ops/runbook/deployment.md'), content: knowledgeMd('部署运维手册') },
    { path: p('docs/ops/runbook/incident-response.md'), content: knowledgeMd('故障响应手册') },
    { path: p('docs/ops/runbook/monitoring.md'), content: knowledgeMd('监控手册') },
    // helm/
    { path: p('helm/Chart.yaml'), content: `apiVersion: v2\nname: ${app}\nversion: 0.1.0\nappVersion: "0.1.0"\n` },
    { path: p('helm/values/dev.yaml'), content: emptyYaml() },
    { path: p('helm/values/staging.yaml'), content: emptyYaml() },
    { path: p('helm/values/prod.yaml'), content: emptyYaml() },
    // .github/workflows/
    { path: p('.github/workflows/ci.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/cd.yaml'), content: emptyYaml() },
    // root files
    { path: p('orchestrator.yaml'), content: `# ${app} Pipeline Orchestrator\nmode: supervised\n` },
    { path: p('.githooks/commit-msg'), content: '#!/bin/sh\n# Enforce TASK reference in commit message\n' },
    { path: p('.pre-commit-config.yaml'), content: emptyYaml() },
    { path: p('docker-compose.yaml'), content: `# ${app} local dev environment\nversion: "3.8"\nservices: {}\n` },
    { path: p('.env.example'), content: `# ${app} environment variables\n` },
    { path: p('Makefile'), content: `# ${app} Makefile\n.PHONY: build test deploy\n\nbuild:\n\t@echo "build"\n\ntest:\n\t@echo "test"\n\ndeploy:\n\t@echo "deploy"\n` },
  ];
}

// ─── §8.3 Solo Monorepo 根目录 ────────────────────────────────────────────

function buildMonorepoRoot(productName: string): ProductFileEntry[] {
  return [
    { path: 'packages/shared-types/.gitkeep', content: EMPTY },
    { path: '.github/workflows/monorepo-orchestrator.yaml', content: emptyYaml() },
    { path: 'OWNERS', content: ownersFile(productName) },
    { path: 'README.md', content: readmeFile(productName, `${productName} Solo Monorepo`) },
  ];
}

// ─── 团队版入口（各子仓库独立路径） ───────────────────────────────────────

/**
 * 团队版产品线仓库根文件列表（路径相对于 {workDir}/{plSlug}/）
 * 内容与 Solo Monorepo 中的产品线层一致，但相对路径从仓库根开始
 */
export function buildTeamProductLineFiles(productName: string): ProductFileEntry[] {
  return [
    // docs/
    { path: 'docs/overview.md', content: overviewMd(`${productName} 产品线`, '产品线概述：背景、愿景、管辖领域、核心目标。') },
    { path: 'docs/VIEWS.yaml', content: emptyYaml() },
    { path: 'docs/features/.gitkeep', content: EMPTY },
    { path: 'docs/journeys/.gitkeep', content: EMPTY },
    { path: 'docs/help-center/guides/.gitkeep', content: EMPTY },
    { path: 'docs/help-center/faq/.gitkeep', content: EMPTY },
    { path: 'docs/help-center/troubleshooting/.gitkeep', content: EMPTY },
    { path: 'docs/help-center/release-notes/.gitkeep', content: EMPTY },
    { path: 'docs/help-center/_index.yaml', content: INDEX_YAML },
    { path: 'docs/delivery/roadmap.md', content: roadmapMd(`${productName} 产品线交付`) },
    { path: 'docs/delivery/breakdown/strategy-status.yaml', content: INDEX_YAML },
    // knowledge/
    { path: 'knowledge/GLOSSARY.md', content: knowledgeMd('跨域统一语言词汇表') },
    { path: 'knowledge/context-map.md', content: knowledgeMd('领域间边界地图') },
    { path: 'knowledge/data-model.md', content: knowledgeMd('跨域共享数据模型') },
    { path: 'knowledge/integration-patterns.md', content: knowledgeMd('跨域集成规范') },
    { path: 'knowledge/shared-events.yaml', content: emptyYaml() },
    { path: 'knowledge/scenarios/.gitkeep', content: EMPTY },
    { path: 'knowledge/adr/.gitkeep', content: EMPTY },
    // strategy/
    { path: 'strategy/roadmap.md', content: roadmapMd(`${productName} 战略`) },
    { path: 'strategy/prd/_index.yaml', content: INDEX_YAML },
    { path: 'strategy/gap-analysis/.gitkeep', content: EMPTY },
    { path: 'strategy/research/_index.yaml', content: INDEX_YAML },
    { path: 'strategy/research/archive/.gitkeep', content: EMPTY },
    // registry/
    { path: 'registry/domains.yaml', content: emptyYaml() },
    { path: 'registry/domain-status.yaml', content: emptyYaml() },
    { path: 'registry/strategy-status.yaml', content: emptyYaml() },
    // environments/
    { path: 'environments/dev/.gitkeep', content: EMPTY },
    { path: 'environments/staging/.gitkeep', content: EMPTY },
    { path: 'environments/prod/.gitkeep', content: EMPTY },
    // governance/
    { path: 'governance/approval-rules.yaml', content: emptyYaml() },
    { path: 'governance/rbac.yaml', content: emptyYaml() },
    { path: 'governance/resource-allocation.yaml', content: emptyYaml() },
    // .github/workflows/
    { path: '.github/workflows/ci.yaml', content: emptyYaml() },
    { path: '.github/workflows/cross-domain-test.yaml', content: emptyYaml() },
    { path: '.github/workflows/product-release.yaml', content: emptyYaml() },
    { path: '.github/workflows/product-rollback.yaml', content: emptyYaml() },
    // root files
    { path: 'OWNERS', content: ownersFile(`${productName} Product Line`) },
    { path: 'README.md', content: readmeFile(`${productName} 产品线`, '产品线入门指南。') },
  ];
}

/**
 * 团队版 Domain 仓库根文件列表（路径相对于 {workDir}/{domainSlug}/）
 */
export function buildTeamDomainFiles(domainName: string, productName: string): ProductFileEntry[] {
  return [
    // docs/
    { path: 'docs/overview.md', content: overviewMd(`${productName} ${domainName}`, '领域概述：边界定义、管辖应用清单、上下游集成关系。') },
    { path: 'docs/VIEWS.yaml', content: emptyYaml() },
    { path: 'docs/features/.gitkeep', content: EMPTY },
    { path: 'docs/delivery/breakdown/app-status.yaml', content: INDEX_YAML },
    { path: 'docs/journeys/.gitkeep', content: EMPTY },
    { path: 'docs/strategy/roadmap.md', content: roadmapMd(`${productName} ${domainName}`) },
    { path: 'docs/strategy/okr.md', content: knowledgeMd('领域 OKR') },
    { path: 'docs/qa/test-cases/_index.yaml', content: INDEX_YAML },
    { path: 'docs/qa/test-plans/.gitkeep', content: EMPTY },
    { path: 'docs/qa/reports/_index.yaml', content: INDEX_YAML },
    // knowledge/
    { path: 'knowledge/GLOSSARY.md', content: knowledgeMd('域内统一语言词汇表') },
    { path: 'knowledge/context-map.md', content: knowledgeMd('域内上下文地图') },
    { path: 'knowledge/domain-data-model.md', content: knowledgeMd('域内共享数据模型') },
    { path: 'knowledge/integration-patterns.md', content: knowledgeMd('域内集成规范') },
    { path: 'knowledge/shared-events.yaml', content: emptyYaml() },
    { path: 'knowledge/scenarios/.gitkeep', content: EMPTY },
    // registry/
    { path: 'registry/apps.yaml', content: emptyYaml() },
    { path: 'registry/sdd-status.yaml', content: emptyYaml() },
    { path: 'registry/delivery-status.yaml', content: emptyYaml() },
    // environments/
    { path: 'environments/dev/env.yaml', content: emptyYaml() },
    { path: 'environments/dev/overrides.yaml', content: emptyYaml() },
    { path: 'environments/staging/.gitkeep', content: EMPTY },
    { path: 'environments/prod/.gitkeep', content: EMPTY },
    // .github/workflows/
    { path: '.github/workflows/ci.yaml', content: emptyYaml() },
    { path: '.github/workflows/domain-release.yaml', content: emptyYaml() },
    { path: '.github/workflows/domain-rollback.yaml', content: emptyYaml() },
    { path: '.github/workflows/integration-test.yaml', content: emptyYaml() },
    // root files
    { path: 'OWNERS', content: ownersFile(`${productName} ${domainName} Domain`) },
    { path: 'README.md', content: readmeFile(`${productName} ${domainName}`, '领域入门指南。') },
  ];
}

/**
 * 团队版 App 仓库根文件列表（路径相对于 {workDir}/apps/{appSlug}/）
 */
export function buildTeamAppFiles(appName: string, productName: string): ProductFileEntry[] {
  return [
    // docs/
    { path: 'docs/overview.md', content: overviewMd(appName, '应用概述：功能边界、架构简图、外部依赖。') },
    { path: 'docs/VIEWS.yaml', content: emptyYaml() },
    { path: 'docs/journeys/.gitkeep', content: EMPTY },
    { path: 'docs/product/prd/_index.yaml', content: INDEX_YAML },
    { path: 'docs/product/architecture/_index.yaml', content: INDEX_YAML },
    { path: 'docs/product/contracts/openapi/.gitkeep', content: EMPTY },
    { path: 'docs/product/contracts/_index.yaml', content: INDEX_YAML },
    { path: 'docs/delivery/roadmap.md', content: roadmapMd(`${appName} 应用`) },
    { path: 'docs/delivery/risk-register.md', content: knowledgeMd('风险登记簿') },
    { path: 'docs/delivery/plan/_index.yaml', content: INDEX_YAML },
    { path: 'docs/delivery/task/_index.yaml', content: INDEX_YAML },
    { path: 'docs/delivery/releases/_index.yaml', content: INDEX_YAML },
    { path: 'docs/delivery/archive/.gitkeep', content: EMPTY },
    { path: 'docs/features/.gitkeep', content: EMPTY },
    { path: 'docs/ops/runbook/deployment.md', content: knowledgeMd('部署运维手册') },
    { path: 'docs/ops/runbook/incident-response.md', content: knowledgeMd('故障响应手册') },
    { path: 'docs/ops/runbook/monitoring.md', content: knowledgeMd('监控手册') },
    // helm/
    { path: 'helm/Chart.yaml', content: `apiVersion: v2\nname: ${appName}\nversion: 0.1.0\nappVersion: "0.1.0"\n` },
    { path: 'helm/values/dev.yaml', content: emptyYaml() },
    { path: 'helm/values/staging.yaml', content: emptyYaml() },
    { path: 'helm/values/prod.yaml', content: emptyYaml() },
    // .github/workflows/
    { path: '.github/workflows/ci.yaml', content: emptyYaml() },
    { path: '.github/workflows/cd.yaml', content: emptyYaml() },
    // root files
    { path: 'orchestrator.yaml', content: `# ${appName} Pipeline Orchestrator\nmode: supervised\n` },
    { path: '.githooks/commit-msg', content: '#!/bin/sh\n# Enforce TASK reference in commit message\n' },
    { path: '.pre-commit-config.yaml', content: emptyYaml() },
    { path: 'docker-compose.yaml', content: `# ${appName} local dev environment\nversion: "3.8"\nservices: {}\n` },
    { path: '.env.example', content: `# ${appName} environment variables\n` },
    { path: 'Makefile', content: `# ${appName} Makefile\n.PHONY: build test deploy\n\nbuild:\n\t@echo "build"\n\ntest:\n\t@echo "test"\n\ndeploy:\n\t@echo "deploy"\n` },
    { path: 'README.md', content: readmeFile(appName, `${productName} ${appName} 应用`) },
  ];
}

/**
 * 团队版父工作目录中的 .xingjing/config.yaml
 * 记录产品结构信息，作为多仓库的元数据入口
 */
export function buildTeamRootConfig(
  productName: string,
  plSlug: string,
  domainSlugs: string[],
  appSlugs: string[],
): ProductFileEntry[] {
  return [
    {
      path: '.xingjing/config.yaml',
      content: [
        `name: ${productName}`,
        `version: "1.0.0"`,
        `mode: team`,
        `created-at: ${new Date().toISOString()}`,
        `product-line: ${plSlug}`,
        `domains:`,
        ...domainSlugs.map(d => `  - ${d}`),
        `apps:`,
        ...appSlugs.map(a => `  - ${a}`),
        '',
      ].join('\n'),
    },
  ];
}

// ─── 主入口 ───────────────────────────────────────────────────────────────

/**
 * 根据产品名、首个应用名及编码，生成完整的 Solo Monorepo 文件清单
 * @param productName 产品名（原始输入，用于文档内容）
 * @param appName     首个应用名（原始输入，用于文档内容）
 * @param productCode 产品英文编码，直接用作产品线目录名（{productCode}-pl）和 Domain 目录名（{productCode}-domain）
 * @param appCode     应用英文编码，直接用作 App 目录名
 * @returns 文件清单（path 相对于 workDir）
 */
export function buildProductFileList(
  productName: string,
  appName: string,
  productCode: string,
  appCode: string,
): ProductFileEntry[] {
  const pl = `${productCode}-pl`;
  const app = appCode;

  return [
    // .xingjing/config.yaml（星静自身配置）
    {
      path: '.xingjing/config.yaml',
      content: [
        `name: ${productName}`,
        `version: "1.0.0"`,
        `created-at: ${new Date().toISOString()}`,
        `product-line: ${pl}`,
        `apps:`,
        `  - ${app}`,
        '',
      ].join('\n'),
    },
    // .xingjing/solo/ 子目录（Solo 模式数据存储）
    { path: '.xingjing/solo/focus.yaml', content: 'items: []\n' },
    { path: '.xingjing/solo/metrics.yaml', content: 'businessMetrics: []\nmetricsHistory: []\nfeatureUsage: []\n' },
    { path: '.xingjing/solo/competitors.yaml', content: 'items: []\n' },
    { path: '.xingjing/solo/feature-flags.yaml', content: 'flags: []\n' },
    { path: '.xingjing/solo/hypotheses/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/feature-ideas/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/adrs/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/releases/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/knowledge/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/feedbacks/.gitkeep', content: EMPTY },
    { path: '.xingjing/solo/tasks/.gitkeep', content: EMPTY },
    // .opencode/agents/ — Solo Agent 定义文件
    { path: '.opencode/agents/product-brain.md', content: agentMdContent('product-brain', 'AI产品搭档', '🧠', '#1264e5', '#e6f0ff', '#91c5ff', ['需求分析', '假设拆解', '用户洞察', '功能优先级'], '以产品经理视角分析目标，拆解为可验证的假设和功能点') },
    { path: '.opencode/agents/eng-brain.md', content: agentMdContent('eng-brain', 'AI工程搭档', '⚙️', '#08979c', '#e6fffb', '#87e8de', ['技术方案', '代码实现', 'Bug 修复', '部署执行'], '选择最简技术方案，直接生成可运行代码，无需评审') },
    { path: '.opencode/agents/growth-brain.md', content: agentMdContent('growth-brain', 'AI增长搭档', '📈', '#d46b08', '#fff7e6', '#ffd591', ['用户获取', '留存策略', '文案生成', '社区运营'], '制定增长策略，生成营销文案，规划用户触达方案') },
    { path: '.opencode/agents/ops-brain.md', content: agentMdContent('ops-brain', 'AI运营搭档', '🔧', '#389e0d', '#f6ffed', '#b7eb8f', ['数据监控', '发布管理', '客服回复', '故障处理'], '监控生产环境，处理用户反馈，执行日常运营任务') },
    // §8.3 根目录
    ...buildMonorepoRoot(productName),
    // §7.1 平台层
    ...buildGovernanceStandards(),
    // §7.2 产品线层
    ...buildProductLine(pl, productName),
    // §7.4 应用层
    ...buildApp(app, productName),
  ];
}
