/**
 * 产品目录结构定义（Solo Monorepo）
 *
 * 从 SolidJS 版本移植，严格对照 KNOWLEDGE-LIFECYCLE.md §7.1-7.4 + §8.3
 * 导出 buildProductFileList(productName, appName) 生成完整文件清单
 */

// ─── 工具函数 ────────────────────────────────────────────────────────────────

/** 将任意字符串转为 kebab-case */
function toKebabCase(str: string): string {
  return str
    .trim()
    .replace(/[\s_]+/g, '-')
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9\u4e00-\u9fff-]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

// ─── 文件条目类型 ─────────────────────────────────────────────────────────────

export interface ProductFileEntry {
  /** 相对于 workDir 的路径 */
  path: string;
  /** 文件初始内容 */
  content: string;
}

// ─── 内容生成辅助函数 ─────────────────────────────────────────────────────────

const EMPTY = '';
const INDEX_YAML = 'items: []\n';

function mdFrontmatter(meta: Record<string, string>): string {
  const lines = Object.entries(meta).map(([k, v]) => `${k}: ${v}`);
  return `---\n${lines.join('\n')}\n---\n\n`;
}

function overviewMd(title: string, description: string): string {
  return mdFrontmatter({ title, lifecycle: 'living', 'created-at': new Date().toISOString().slice(0, 10) })
    + `# ${title}\n\n${description}\n`;
}

function knowledgeMd(title: string): string {
  return mdFrontmatter({ title, lifecycle: 'living', 'created-at': new Date().toISOString().slice(0, 10) })
    + `# ${title}\n`;
}

function roadmapMd(scope: string): string {
  return mdFrontmatter({ title: `${scope} Roadmap`, lifecycle: 'living', 'created-at': new Date().toISOString().slice(0, 10) })
    + `# ${scope} Roadmap\n\n## Milestones\n\n_TODO_\n`;
}

function emptyYaml(): string {
  return '# Auto-generated by xingjing\n';
}

function ownersFile(name: string): string {
  return `# ${name}\n# Add owner GitHub handles below\n`;
}

function readmeFile(title: string, description: string): string {
  return `# ${title}\n\n${description}\n`;
}

// ─── §7.1 平台层 governance-standards/ ─────────────────────────────────────

function buildGovernanceStandards(): ProductFileEntry[] {
  const p = (f: string) => `governance-standards/${f}`;
  return [
    { path: p('schemas/prd-schema.json'), content: '{}' },
    { path: p('schemas/sdd-schema.json'), content: '{}' },
    { path: p('schemas/contract-schema.json'), content: '{}' },
    { path: p('schemas/plan-schema.json'), content: '{}' },
    { path: p('schemas/strategy-prd-schema.json'), content: '{}' },
    { path: p('schemas/benchmark-schema.json'), content: '{}' },
    { path: p('templates/PRD-template.md'), content: '# PRD Template\n' },
    { path: p('templates/SDD-template.md'), content: '# SDD Template\n' },
    { path: p('templates/CONTRACT-template.md'), content: '# CONTRACT Template\n' },
    { path: p('templates/PLAN-template.md'), content: '# PLAN Template\n' },
    { path: p('templates/TASK-template.md'), content: '# TASK Template\n' },
    { path: p('templates/STRATEGY-PRD-template.md'), content: '# Strategy PRD Template\n' },
    { path: p('templates/BENCHMARK-template.md'), content: '# BENCHMARK Template\n' },
    { path: p('templates/FEATURE-template.md'), content: '# FEATURE Template\n' },
    { path: p('templates/RUNBOOK-template.md'), content: '# RUNBOOK Template\n' },
    { path: p('templates/ROADMAP-template.md'), content: '# ROADMAP Template\n' },
    { path: p('templates/PIPELINE-template.yaml'), content: emptyYaml() },
    { path: p('templates/_index-template.yaml'), content: INDEX_YAML },
    { path: p('templates/platform-adapters/.gitkeep'), content: EMPTY },
    { path: p('templates/scaffold/.gitkeep'), content: EMPTY },
    { path: p('quality-gates/sdd-completeness.yaml'), content: emptyYaml() },
    { path: p('quality-gates/ci-gates.yaml'), content: emptyYaml() },
    { path: p('quality-gates/security-compliance.yaml'), content: emptyYaml() },
    { path: p('quality-gates/engineering-metrics.yaml'), content: emptyYaml() },
    { path: p('conventions/naming.yaml'), content: emptyYaml() },
    { path: p('conventions/versioning.yaml'), content: emptyYaml() },
    { path: p('conventions/branching.yaml'), content: emptyYaml() },
    { path: p('capabilities/agents/.gitkeep'), content: EMPTY },
    { path: p('capabilities/skills/.gitkeep'), content: EMPTY },
    { path: p('capabilities/platform-overlays/.gitkeep'), content: EMPTY },
    { path: p('capabilities/registry.yaml'), content: emptyYaml() },
  ];
}

// ─── §7.2 产品线层 {pl}/ ──────────────────────────────────────────────────

function buildProductLine(pl: string, productName: string): ProductFileEntry[] {
  const p = (f: string) => `${pl}/${f}`;
  return [
    { path: p('docs/overview.md'), content: overviewMd(`${productName} 产品线`, '产品线概述：背景、愿景、管辖领域、核心目标。') },
    { path: p('docs/VIEWS.yaml'), content: emptyYaml() },
    { path: p('docs/features/.gitkeep'), content: EMPTY },
    { path: p('docs/journeys/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/guides/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/faq/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/troubleshooting/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/release-notes/.gitkeep'), content: EMPTY },
    { path: p('docs/help-center/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/roadmap.md'), content: roadmapMd(`${productName} 产品线交付`) },
    { path: p('docs/delivery/breakdown/strategy-status.yaml'), content: INDEX_YAML },
    { path: p('knowledge/GLOSSARY.md'), content: knowledgeMd('跨域统一语言词汇表') },
    { path: p('knowledge/context-map.md'), content: knowledgeMd('领域间边界地图') },
    { path: p('knowledge/data-model.md'), content: knowledgeMd('跨域共享数据模型') },
    { path: p('knowledge/integration-patterns.md'), content: knowledgeMd('跨域集成规范') },
    { path: p('knowledge/shared-events.yaml'), content: emptyYaml() },
    { path: p('knowledge/scenarios/.gitkeep'), content: EMPTY },
    { path: p('knowledge/adr/.gitkeep'), content: EMPTY },
    { path: p('strategy/roadmap.md'), content: roadmapMd(`${productName} 战略`) },
    { path: p('strategy/prd/_index.yaml'), content: INDEX_YAML },
    { path: p('strategy/gap-analysis/.gitkeep'), content: EMPTY },
    { path: p('strategy/research/_index.yaml'), content: INDEX_YAML },
    { path: p('strategy/research/archive/.gitkeep'), content: EMPTY },
    { path: p('registry/domains.yaml'), content: emptyYaml() },
    { path: p('registry/domain-status.yaml'), content: emptyYaml() },
    { path: p('registry/strategy-status.yaml'), content: emptyYaml() },
    { path: p('environments/dev/.gitkeep'), content: EMPTY },
    { path: p('environments/staging/.gitkeep'), content: EMPTY },
    { path: p('environments/prod/.gitkeep'), content: EMPTY },
    { path: p('governance/approval-rules.yaml'), content: emptyYaml() },
    { path: p('governance/rbac.yaml'), content: emptyYaml() },
    { path: p('governance/resource-allocation.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/ci.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/cross-domain-test.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/product-release.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/product-rollback.yaml'), content: emptyYaml() },
    { path: p('OWNERS'), content: ownersFile(`${productName} Product Line`) },
    { path: p('README.md'), content: readmeFile(`${productName} 产品线`, '产品线入门指南。') },
  ];
}

// ─── §7.3 领域层 {domain}/ ────────────────────────────────────────────────

function buildDomain(domain: string, productName: string): ProductFileEntry[] {
  const p = (f: string) => `${domain}/${f}`;
  return [
    { path: p('docs/overview.md'), content: overviewMd(`${productName} 领域`, '领域概述：边界定义、管辖应用清单、上下游集成关系。') },
    { path: p('docs/VIEWS.yaml'), content: emptyYaml() },
    { path: p('docs/features/.gitkeep'), content: EMPTY },
    { path: p('docs/delivery/breakdown/app-status.yaml'), content: INDEX_YAML },
    { path: p('docs/journeys/.gitkeep'), content: EMPTY },
    { path: p('docs/strategy/roadmap.md'), content: roadmapMd(`${productName} 领域`) },
    { path: p('docs/strategy/okr.md'), content: knowledgeMd('领域 OKR') },
    { path: p('docs/qa/test-cases/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/qa/test-plans/.gitkeep'), content: EMPTY },
    { path: p('docs/qa/reports/_index.yaml'), content: INDEX_YAML },
    { path: p('knowledge/GLOSSARY.md'), content: knowledgeMd('域内统一语言词汇表') },
    { path: p('knowledge/context-map.md'), content: knowledgeMd('域内上下文地图') },
    { path: p('knowledge/domain-data-model.md'), content: knowledgeMd('域内共享数据模型') },
    { path: p('knowledge/integration-patterns.md'), content: knowledgeMd('域内集成规范') },
    { path: p('knowledge/shared-events.yaml'), content: emptyYaml() },
    { path: p('knowledge/scenarios/.gitkeep'), content: EMPTY },
    { path: p('registry/apps.yaml'), content: emptyYaml() },
    { path: p('registry/sdd-status.yaml'), content: emptyYaml() },
    { path: p('registry/delivery-status.yaml'), content: emptyYaml() },
    { path: p('environments/dev/env.yaml'), content: emptyYaml() },
    { path: p('environments/dev/overrides.yaml'), content: emptyYaml() },
    { path: p('environments/staging/.gitkeep'), content: EMPTY },
    { path: p('environments/prod/.gitkeep'), content: EMPTY },
    { path: p('.github/workflows/ci.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/domain-release.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/domain-rollback.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/integration-test.yaml'), content: emptyYaml() },
    { path: p('OWNERS'), content: ownersFile(`${productName} Domain`) },
    { path: p('README.md'), content: readmeFile(`${productName} 领域`, '领域入门指南。') },
  ];
}

// ─── §7.4 应用层 apps/{app}/ ──────────────────────────────────────────────

function buildApp(app: string, productName: string): ProductFileEntry[] {
  const p = (f: string) => `apps/${app}/${f}`;
  return [
    { path: p('docs/overview.md'), content: overviewMd(`${app}`, '应用概述：功能边界、架构简图、外部依赖。') },
    { path: p('docs/VIEWS.yaml'), content: emptyYaml() },
    { path: p('docs/journeys/.gitkeep'), content: EMPTY },
    { path: p('docs/product/prd/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/product/architecture/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/product/contracts/openapi/.gitkeep'), content: EMPTY },
    { path: p('docs/product/contracts/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/roadmap.md'), content: roadmapMd(`${app} 应用`) },
    { path: p('docs/delivery/risk-register.md'), content: knowledgeMd('风险登记簿') },
    { path: p('docs/delivery/plan/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/task/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/releases/_index.yaml'), content: INDEX_YAML },
    { path: p('docs/delivery/archive/.gitkeep'), content: EMPTY },
    { path: p('docs/features/.gitkeep'), content: EMPTY },
    { path: p('docs/ops/runbook/deployment.md'), content: knowledgeMd('部署运维手册') },
    { path: p('docs/ops/runbook/incident-response.md'), content: knowledgeMd('故障响应手册') },
    { path: p('docs/ops/runbook/monitoring.md'), content: knowledgeMd('监控手册') },
    { path: p('helm/Chart.yaml'), content: `apiVersion: v2\nname: ${app}\nversion: 0.1.0\nappVersion: "0.1.0"\n` },
    { path: p('helm/values/dev.yaml'), content: emptyYaml() },
    { path: p('helm/values/staging.yaml'), content: emptyYaml() },
    { path: p('helm/values/prod.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/ci.yaml'), content: emptyYaml() },
    { path: p('.github/workflows/cd.yaml'), content: emptyYaml() },
    { path: p('orchestrator.yaml'), content: `# ${app} Pipeline Orchestrator\nmode: supervised\n` },
    { path: p('.githooks/commit-msg'), content: '#!/bin/sh\n# Enforce TASK reference in commit message\n' },
    { path: p('.pre-commit-config.yaml'), content: emptyYaml() },
    { path: p('docker-compose.yaml'), content: `# ${app} local dev environment\nversion: "3.8"\nservices: {}\n` },
    { path: p('.env.example'), content: `# ${app} environment variables\n` },
    { path: p('Makefile'), content: `# ${app} Makefile\n.PHONY: build test deploy\n\nbuild:\n\t@echo "build"\n\ntest:\n\t@echo "test"\n\ndeploy:\n\t@echo "deploy"\n` },
  ];
}

// ─── §8.3 Solo Monorepo 根目录 ────────────────────────────────────────────

function buildMonorepoRoot(productName: string): ProductFileEntry[] {
  return [
    { path: 'packages/shared-types/.gitkeep', content: EMPTY },
    { path: '.github/workflows/monorepo-orchestrator.yaml', content: emptyYaml() },
    { path: 'OWNERS', content: ownersFile(productName) },
    { path: 'README.md', content: readmeFile(productName, `${productName} Solo Monorepo`) },
  ];
}

// ─── 主入口 ───────────────────────────────────────────────────────────────

/**
 * 根据产品名和首个应用名，生成完整的 Solo Monorepo 文件清单
 * @param productName 产品名（原始输入）
 * @param appName     首个应用英文简称（原始输入）
 * @returns 文件清单（path 相对于 workDir）
 */
export function buildProductFileList(
  productName: string,
  appName: string,
): ProductFileEntry[] {
  const kebab = toKebabCase(productName);
  const pl = `${kebab}-pl`;
  const domain = `${kebab}-domain`;
  const app = toKebabCase(appName);

  return [
    // .xingjing/config.yaml（星静自身配置）
    {
      path: '.xingjing/config.yaml',
      content: [
        `name: ${productName}`,
        `version: "1.0.0"`,
        `created-at: ${new Date().toISOString()}`,
        `product-line: ${pl}`,
        `domain: ${domain}`,
        `apps:`,
        `  - ${app}`,
        '',
      ].join('\n'),
    },
    // §8.3 根目录
    ...buildMonorepoRoot(productName),
    // §7.1 平台层
    ...buildGovernanceStandards(),
    // §7.2 产品线层
    ...buildProductLine(pl, productName),
    // §7.3 领域层
    ...buildDomain(domain, productName),
    // §7.4 应用层
    ...buildApp(app, productName),
  ];
}

/**
 * 将文件清单转换为目录树结构（用于 UI 展示）
 */
export interface DirTreeNode {
  name: string;
  path: string;
  isDir: boolean;
  children: DirTreeNode[];
}

export function buildDirTree(files: ProductFileEntry[]): DirTreeNode[] {
  const root: DirTreeNode[] = [];

  for (const f of files) {
    const parts = f.path.split('/');
    let current = root;

    for (let i = 0; i < parts.length; i++) {
      const name = parts[i];
      const isDir = i < parts.length - 1;
      const path = parts.slice(0, i + 1).join('/');

      let node = current.find((n) => n.name === name);
      if (!node) {
        node = { name, path, isDir, children: [] };
        current.push(node);
      }
      if (isDir) {
        current = node.children;
      }
    }
  }

  return root;
}
